### ISSUE TITLE
Passing data to gameservers at allocation time

### ISSUE THREAD

**Issue by Omegastick** [googleforgames/agones#1087]
**Is your feature request related to a problem? Please describe.**
I'd like to pass some data from the matchmaking server to a game server at allocation time (player usernames and access tokens).

**Describe the solution you'd like**
The most reasonable thing to do seems to use the Allocation definition to set some annotation metadata, and then access that in the container at runtime.

However, setting environment variables from annotations (see "Additional context" below) doesn't work. Presumably because environment variables are set at startup, and not updated afterwards (see https://github.com/kubernetes/kubernetes/issues/19367).

Is there a de-facto way to do this in Agones? If not, updating the container's environment variables at runtime seems possible on the Agones side.

**Describe alternatives you've considered**
I've considered opening an HTTP server on the game server, but dynamically allocating HTTP ports with Agones doesn't seem simple. It also adds a lot of complexity that is ultimately unnecessary.

**Additional context**
Here's an example fleet definition:
```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: my-game
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 7654
          protocol: TCP
      template:
        spec:
          containers:
            - name: my-game
              image: gcr.io/my-project/my-game
              imagePullPolicy: Always
              env:
                - name: PLAYER_1_USERNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['player_1_username']
                - name: PLAYER_2_USERNAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['player_2_username']
                - name: PLAYER_1_TOKEN
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['player_1_token']
                - name: PLAYER_2_TOKEN
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['player_2_token']

```
Here's an example allocation definition:
```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  required:
    matchLabels:
      agones.dev/fleet: my-fleet
  metadata:
    annotations:
      player_1_username: Bob
      player_1_token: asd
      player_2_username: Steve
      player_2_token: sdf

```
