### ISSUE TITLE
Please create a root OWNERS file for agones

### ISSUE THREAD

**Issue by fejta** [googleforgames/agones#1112]
Can you create OWNERS files? At least one in the root dir.

/assign @roberthbailey 

```yaml
{
 insertId: "x0pnb4f8jk0fp"  
 jsonPayload: {
  author: "pooneh-m"   
  component: "hook"   
  event-GUID: "7a7a5af0-eeae-11e9-92e0-9607e4f41e57"   
  event-type: "pull_request"   
  file: "prow/plugins/approve/approvers/owners.go:164"   
  func: "k8s.io/test-infra/prow/plugins/approve/approvers.Owners.GetSuggestedApprovers"   
  level: "warning"   
  msg: "Couldn't find/suggest approvers for each files. Unapproved: [""]"   
  org: "googleforgames"   
  plugin: "approve"   
  pr: 1110   
  repo: "agones"   
  url: "https://github.com/googleforgames/agones/pull/1110"   
 }
 labels: {…}  
 logName: "projects/oss-prow/logs/hook"  
 receiveTimestamp: "2019-10-14T18:14:48.747545067Z"  
 resource: {…}  
 severity: "ERROR"  
 timestamp: "2019-10-14T18:14:41Z"  
}
```
