### ISSUE TITLE
Game Server Allocation advanced filtering: player count, state, reallocation

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#1239]
Dependent on #1033

(Not a detailed design ticket, just putting down the basic idea to get the conversation started)

**Is your feature request related to a problem? Please describe.**
In both session based games and persistent games, it would be useful to be able to do something akin to:
_Just give me a GameServer that has room for 2 (or n number) players, regardless whether it is Allocated or not_

Which would pass back a GameServer if it had capacity available, and if not, would Allocate a whole new one (with enough initial capacity), and return that instead.

This would be useful for:
- Automating matchmaking backfill operations
- matchmaking players to persistent worlds that have capacities (#1034 helps here too)

**Describe the solution you'd like**

Some kind of adjustment to `GameServerAllocation` that accounts for capacity of players that are available. Maybe a way to choose what State(s) are in the Allocation pool? (Ready or Allocated??)

This probably requires much thought, and would want to tie into #1197 so they don't conflict with each other.

**Describe alternatives you've considered**
Having a totally different Allocation path for player capacity based allocations -- but then we will likely end up with a huge number of paths for different types of allocations.,

**Additional context**
Can't think of anything else.

**Comment by markmandel** [comment]
## Objective

Already defined above


## Background

These are terms that are currently used in Player Tracking:



*   Player Capacity: Max number of players that could end up in a GameServer 
*   Player Count: The number of players that are in a GameServer currently
*   Player Availability: Capacity - Count. (this is new for this ticket)


## Requirements and Scale



*   Is a high throughput operation, so will need to have an implementation that allows for this.
*   Will need similar scaling characteristics to current Allocation policy.
*   Will sit behind a feature flag of “PlayerAvailableAllocation”
*   Will still need to adhere to `Packing` and `Distributed` optimisation patterns
*   Will still need to be filterable on `required` and `preferred` match labels/expressions


## Design Ideas

Very similar to what we did with [FleetAutoscaler](https://agones.dev/site/docs/reference/agones_crd_api_reference/#autoscaling.agones.dev/v1.FleetAutoscalerSpec), we add a `policy` section to the `GameServerAllocation` which defines the strategy that the GameServerAllocation will take when allocating. There can then be a subject configuration block under `policy` that would include any needed configuration parameters.

This should be extensible to other types of allocation strategies down the line, and also doesn’t require a breaking change to the existing allocation implementation.

For example, the current way of allocating against Ready GameServers (which would be default, and therefore backward compatible) would become:


```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
  policy: # this is the new part 😃
    type: "Ready"
```


Therefore, to attempt to find a GameServer that has room for _at least_ 2 players that is already Allocated, and if not found, to then find a Ready one that has the same amount or more of capacity, and move it to Allocated, this would look like the following:

```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
  policy:
    type: "Players"
      players:
        available: 2
```


Wherein:



*   `type: "Players"` - means it is allocating against player availability.
*   `type.players` - is the configuration options for the “players” policy
*   `type.players.available` - is the number of players to look for when attempting to find a GameServer.

This would also need to eventually be expanded to the gRPC Allocation Service API, but the same format could be reused.

**Question:** Is "players" too generic a name? It is the structure we are using in Player Tracking, so figured it would be good to be consistent.

### Technical Implementation



*   Much like we keep a [ready cache](https://github.com/googleforgames/agones/blob/master/pkg/gameserverallocations/ready_cache.go), we should also keep a cache of Allocated game servers that have a player availability greater than 0. This may be able to be pre-sorted based on packing rules. This should be the first place that is searched for Allocations that match the label selectors. 
*   If we cannot find a previously Allocated GameServer that matches the criteria required, then we fall back to searching for a Ready GameServer - but with the additional requirement of making sure the players available of the Ready GameServer is greater than or equal to that which is requested.
*   This is likely going to require some refactoring of the <code>[ListenAndAllocate function](https://github.com/googleforgames/agones/blob/master/pkg/gameserverallocations/allocator.go#L436)</code>, as it is currently optimised for only the Ready policy. 


## Alternatives Considered

We could implement a whole new Allocation pathway (which we discussed earlier), which seems untenable.

I couldn’t think of another way of extending `GameServerAllocation` that wouldn’t break backward compatibility or force us into a `v2` version of the CRD - which has other issues as well.

We could try and come up with a solution that is far more flexible and open - but with a narrow set of allocation policy types, this becomes much easier to optimise for and ensure there is scalable throughput.

**Comment by markmandel** [comment]
@pooneh-m do you see any issues here? Especially when it comes to multi-cluster allocation? I couldn't see any, but wanted to double check.

**Comment by markmandel** [comment]
One thought that came to mind - if I send multiple requests for a GameServer with available for 1 player - I shouldn't repeatedly get the same GameServer -- at least not in the some n time period. Otherwise, race condition city.

One thing we could probably take advantage of in that GameServer get refreshed every 30 seconds even if it hasn't changed -- so we can leverage the GameServer capacity cache, such that when we pass back an Allocated GameServer with capacity, it gets removed from the GameServer availability cache. 

That being said, when each GameServer gets refreshed is not in our control - so it would be any time _up to_ 30 seconds -- so this might be a good first step -- but we may also want to keep our own list of GameServers that we hold onto for a little while as "allocated, but via availability" unless it gets genuinely updated (i.e. status change, player count change etc), in which case, update the cache, to try and mitigate this race condition.

**Comment by pooneh-m** [comment]
> @pooneh-m do you see any issues here? Especially when it comes to multi-cluster allocation? I couldn't see any, but wanted to double check.

For multi-cluster allocation, it translates the allocation status to gRPC error; so for example for the lack of capacity, `ResourceExhausted` is used. I think for player capacity the same error should be returned. The API should remain consistent with `GameServerAllocation`.

For the overall API design, I wonder if we should still categorize the player count criterium as part of `required` or `preferred`. 
```
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
    policy:
      type: "Players"
      players:
        available: 2
```
Should it also support range?
It would help to list different user journeys for the design. e.g.:
- allocate a game server with at least 2 player capacity
- allocate a game server with exactly 2 player capacity

If there are multiple criterium, how can we stack rank them? Is it part of the user journey?

**Comment by markmandel** [comment]
> For the overall API design, I wonder if we should still categorize the player count criterium as part of required or preferred.

AAAAAH YES! :cartwheeling:  I was trying to see if there was a way to do something like this, but for whatever reason did not see this path! I like this a lot! Thank you @pooneh-m for this direction! I also love the idea of supporting ranges as well. Makes perfect sense.

I'm actually now wondering if we do away with policy all together, and expand on `required` and `preferred` to cover this use case, but potentially more.

So, say you wanted to do a standard situation of: _give me a game server with an availability of 2 or more players, but if not available, allocate a Ready GameServer_, you could do something like:

```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  preferred:
    - matchLabels:
        agones.dev/fleet: simple-udp
      gameServerState: Allocated # new state filter: allocate from Allocated servers
      players: # new player availability filter
          minAvailable: 2
          maxAvailable: 999
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
    gameServerState: Ready # Allocate out of the Ready Pool (which would be default, so backward compatible)
```

So first pass of the allocation system would look at the `preferred` block (which does have the ability to provide multiple options if the first once cannot be provided), and if it could not find anything, move onto `required` - which would do the usual allocation strategy (or whatever is specied here).

This would remove `policy` from the Allocation design above, which may make optimisation more complex, but does provide a much more flexible set of allocation options.

You could do things like _Give me an already Allocated GameServer with availability for 2 players, but no nothing if you can't find one._, which you absolutely couldn't before, which I think could be quite useful :+1: 

Thoughts?

**Comment by EricFortin** [comment]
> The second one is about `minAvailable` . We should prohibit users to reconnect to the same GameServers, otherwise at some point `minAvailable` could become 0. And we should not return the same `GameServer` twice as a result of 2 consequent calls to `GameServerAllocation` with the same query parameters.

I don't think we should get in the way of a player reconnecting since this is usually a game design decision. Furthermore, if integration has been done correctly, the user reconnecting should have disconnected beforehand so the used capacity wouldn't change. The reconnect flow is supported in multiple games. Also, I am not sure how reactive the player tracking is but if a developer elect to use `packed` as allocation strategy and makes multiple consecutive allocations. I believe we should return the same server as long as there is enough capacity.

I also have a question on the design, will the capacity based allocation also respect allocation strategy? By that I mean in a `packed` model, will it try to allocate allocated game server on the same node if possible?

**Comment by markmandel** [comment]
So to all the points about returning the previously returned GameServer are 100% valid. One thought I had though was to have an extra new element of `hold` - which is to say, "Don't re-allocate this GameServer for _duration_ after it has been Allocated", so something like this:

```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  preferred:
    - matchLabels:
        agones.dev/fleet: simple-udp
      gameServerState: Allocated # new state filter: allocate from Allocated servers
      players: # new player availability filter
          minAvailable: 2
          maxAvailable: 999
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
    gameServerState: Ready # Allocate out of the Ready Pool (which would be default, so backward compatible)
  hold: 5s
```

So this would make the request for the GameServer with at least 2 players, and then give the client 5 seconds to do it's connection and registration before opening it up again for new players to come back in.

This would give you a way to limit the race conditions you might get when re-allocating the same GameServer, but allow for a GameServer to do whatever game specific thing we expect it to do in that time (we could track this on an GameServer Annotation) -- or you could opt out entirely, and leave it at it's default of 0.

The other option is tracking what we expect the capacity _should_ be post Allocation, but I think that's too complicated -- at least for a first pass.

How do we feel about something like that?

> I also have a question on the design, will the capacity based allocation also respect allocation strategy? By that I mean in a packed model, will it try to allocate allocated game server on the same node if possible?

Absolutely - we mentioned that in the initial design :+1: Optimisation strategies are a definite must for sure.

`Packed` would target the Node with the most allocated game servers (which is what is does already), and then look for the most full one.

`Distributed` would likely do it's usual randomisation thing.

That what you expected?

**Comment by markmandel** [comment]
Just gently bumping this, to see if the above makes sense. If so, I can update the design above to incorporate these changes.

**Comment by pooneh-m** [comment]
Perhaps `hold` should be and environment variable vs per request setting. I am not a big fan of timed resource reservation as it get hard to track and predict.

I think a matchmaker should reserve a game server, allocate it for x number of players and release it. When a game server is reserved, it will not be returned to any other match maker until it is ready to accept more players (released). So another approach could be to provide an API call for releasing an allocation lock, controlled by a matchmaker.

**Comment by markmandel** [comment]
> Perhaps hold should be an environment variable vs per request setting. Timed resource reservation will be difficult to track and predict.

Let's remove the `hold` idea for now, your follow up comments provide some interesting insights I want to explore more, and I think we can use for at least the first pass implementation. But I think we (a) need to have _something_ at a per GameServer level, as different types of game server will likely have different connection requirements (lobbies vs game sessions for example). I also think we can solve this on a per GameServer basis using the CRD locking functionality of the K8s api.

>  So another approach could be to provide an API call for releasing an allocation lock, controlled by a matchmaker.

I'm a bit hesitant to add yet another API endpoint -- but your comment here made me realise something cool, we could actually do exactly what you suggest now, but without another API! We can do it with labels, and the Agones game server SDK!

For example, if I did:

```yaml
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  preferred:
    - matchLabels:
        agones.dev/fleet: simple-udp
        agones.dev/sdk-available: "true" # this is important
      gameServerState: Allocated # new state filter: allocate from Allocated servers
      players: # new player availability filter
          minAvailable: 2
          maxAvailable: 999
  required:
    matchLabels:
      agones.dev/fleet: simple-udp
    gameServerState: Ready # Allocate out of the Ready Pool (which would be default, so backward compatible)
  metadata:
    labels:
      agones.dev/sdk-available: "false" # this removes it from the pool
```

So what does this do?

- If the GameServer is Ready, allocate as per normal
- If the GameServer is Allocated, only return it if the `agones.dev/sdk-available` label value is set to true.
- Once Allocated, set `agones.dev/sdk-available` to false.

This would mean if we re-allocated a GameServer that was in an Allocated state, it automatically drops itself out of the pool of re-allocatable GameServers, because it no longer is valid for the search conditions :smile: 

How then would the GameServer set itself to being available again to being re-allocated? It can do this now through SDK.WatchGameServer(...), and then set the label `agones.dev/sdk-available` back to being `true` as appropriate for the game.

The downside here being that it is onto the user to pass the relevant information down to the gameserver (likely through annotations) to determine when it should reset itself - but maybe that's a great first pass at this functionality, and we can then get more sophisticated (maybe extend `hold` to be more intelligent)? as we get more feedback.

(A) Did that make sense and (B) WDYT of that approach?
