### ISSUE TITLE
The command: `kubectl get gs` can display all exported ports.

### ISSUE THREAD

**Issue by xinyu7git** [googleforgames/agones#1262]
**Is your feature request related to a problem? Please describe.**
When i export mulit ports in yaml, It only display one port by using `kubectl  get gs` command
gs.yaml
```
spec:
  ports:
  - name: grpc
    portPolicy: Dynamic
    containerPort: 8501
    protocol: TCP
  - name: http
    portPolicy: Dynamic
    containerPort: 8601
    protocol: TCP
```
kubectl command:
```
NAME                      STATE       ADDRESS          PORT   NODE             AGE
gs-example-nszv8          Ready       172.18.178.251   7095   172-18-178-251   3m44s
```
only one port info for the first port.

**Describe the solution you'd like**
display all ports in `kubectl get gs` , maybe if  port numbers are consecutive , it will be better:
```
NAME                      STATE       ADDRESS          PORT   NODE             AGE
gs-example-nszv8          Ready       172.18.178.251   7095, 7096   172-18-178-251   3m44s
```

**Describe alternatives you've considered**
I want to know all exported ports.
