### ISSUE TITLE
Gameserver failed to start in the namespace with runAsNonRoot pod security context.

### ISSUE THREAD

**Issue by Feng-Yin** [googleforgames/agones#1287]
**What happened**:
Gameserver failed to start in the namespace with runAsNonRoot pod security context.

**What you expected to happen**:
Gameserver can be started normally.

**How to reproduce it (as minimally and precisely as possible)**:
1. Deploy a Gameserver into the namespace with runAsNonRoot pod security context.
2. ```kubectl describe pod <gameserver [pod>```](url) will give an error message: 
```Error: container has runAsNonRoot and image has non-numeric user (agones), cannot verify user is non-root```

**Anything else we need to know?**:
1. The link used for starting minikube with restrict setting: https://minikube.sigs.k8s.io/docs/tutorials/using_psp/
2. need to enable hostNetwork in restricted.PodSecurityPolicy
  ```
  hostNetwork: true
  hostPorts:
  - min: 7000
    max: 8000
  ```

**Environment**:
- Agones version: 1.1.0
- Kubernetes version (use `kubectl version`): 1.16.2
- Cloud provider or hardware configuration: local minikube v1.5.2
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:

**Comment by markmandel** [comment]
Thanks for the bug report!

Kubernetes 1.13 is the supported version for Agones at this time.
https://agones.dev/site/docs/installation/#usage-requirements

Does this error still occur on this version?

Also, can you please provide step by step instructions on how to reproduce?

The exact pod security policy you used, and the an example GameServer we can use to reproduce would be ideal.

Thanks!

**Comment by Feng-Yin** [comment]
The psp.yaml I'm using:
```
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: "*"
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - "*"
  volumes:
  - "*"
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: true
  hostPorts:
  - min: 7000
    max: 8000
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      # Forbid adding the root group.
      - min: 1
        max: 65535
  readOnlyRootFilesystem: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:privileged
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:restricted
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - restricted
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:restricted
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:restricted
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:privileged
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged
subjects:
- kind: Group
  name: system:masters
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:serviceaccounts:kube-system
  apiGroup: rbac.authorization.k8s.io
```
