### ISSUE TITLE
Fleet RollingUpdate strategy is not working correctly with FleetAutoScaler

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1325]
When using `kubectl apply` on a Fleet with FleetAutoscaler with not present `Replicas` in it RollingUpdate strategy works incorrectly.
It scales up from 1 to n disregarding MaxSurge param.

**What happened**:
Created a fleet with maxSurge one and replicas: 5, FAS with buffer of 5. 
Wait until 5 are ready.
Allocated one GS and then update the label scaling from 1 to 5 was in one second time, it should be step by step: remove one - add one. Logs below.

**What you expected to happen**:
Fleet RollingUpdate parameters should be taken into account and should work as expected in any scenario.
The only exception should be when we state `Replicas` parameter explicitly, then it should be used and change GS count in one step.
See Note in [FleetAutoScaler docs](https://1-3-0.agones.dev/site/docs/getting-started/create-fleetautoscaler/#7-change-autoscaling-parameters)

**How to reproduce it (as minimally and precisely as possible)**:
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: flat-example
spec:
  replicas: 5
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        foo: bazar
    spec:
      ports:
      - name: default
        portPolicy: Dynamic
        containerPort: 26000
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: simple-udp
            image: gcr.io/agones-images/udp-server:0.16
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: server-autoscaler
spec:
  fleetName: flat-example
  policy:
    type: Buffer
    buffer:
      bufferSize: 5
      minReplicas: 5
      maxReplicas: 10
```
1. kubectl apply -f fleetWithFAS.yaml
1. remove replicas, edit labels in a file
1. kubectl apply -f fleetWithFAS.yaml
This steps leads to no rolling updates

**Anything else we need to know?**:
There could be an issue with Fleet controller.
Another option to consider is adding a pointer to `Replicas` might fix an issue as `ReplicaSet` in Kubernetes.
Replicaset does contain omitempty:
```
// ReplicaSetSpec is the specification of a ReplicaSet.
type ReplicaSetSpec struct {
	// Replicas is the number of desired replicas.
	// This is a pointer to distinguish between explicit zero and unspecified.
	// Defaults to 1.
	// More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/#what-is-a-replicationcontroller
	// +optional
	Replicas *int32 `json:"replicas,omitempty" protobuf:"varint,1,opt,name=replicas"`
```

**Environment**:
- Agones version:  1.4 (dev)
- Kubernetes version (use `kubectl version`): 1.13
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
```
5m41s       Normal    ScalingGameServerSet    Fleet             Scaling active GameServerSet flat-example-2rpmh from 5 to 6                                                                              
2m29s       Normal    ScalingGameServerSet    Fleet             Scaling inactive GameServerSet flat-example-2rpmh from 6 to 5                                                                            
2m26s       Normal    ScalingGameServerSet    Fleet             Scaling inactive GameServerSet flat-example-2rpmh from 5 to 4                                                                            
2m20s       Normal    ScalingGameServerSet    Fleet             Scaling inactive GameServerSet flat-example-2rpmh from 4 to 3                                                                            
2m11s       Normal    CreatingGameServerSet   Fleet             Created GameServerSet flat-example-t7bv5                                                                                                 
2m10s       Normal    ScalingGameServerSet    Fleet             Scaling inactive GameServerSet flat-example-2rpmh from 3 to 2                                                                            
2m10s       Normal    ScalingGameServerSet    Fleet             Scaling active GameServerSet flat-example-t7bv5 from 1 to 2                                                                              
2m10s       Normal    ScalingGameServerSet    Fleet             Scaling active GameServerSet flat-example-t7bv5 from 2 to 3                                                                              
2m10s       Normal    ScalingGameServerSet    Fleet             Scaling active GameServerSet flat-example-t7bv5 from 3 to 4                                                                              
2m9s        Normal    ScalingGameServerSet    Fleet             Scaling active GameServerSet flat-example-t7bv5 from 4 to 5     
```
- Others:
