### ISSUE TITLE
SDK Server ignores custom GameServer configuration file in local mode

### ISSUE THREAD

**Issue by cadfoot** [googleforgames/agones#1508]
**What happened**:
SDK Server ignores custom GameServer configuration file in local mode

**What you expected to happen**:
SDK Server initializes with provided `GameServer` configuration when running locally

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a `GameServer` config (health check is disabled in this example)
```
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "simple-udp-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7654
  health:
    disabled: true
```
2. Run SDK Server locally with created config
```
sdk-server.windows.amd64.exe --local -f gameserver.yaml
```
3. Request game server information
```
curl -GET "http://localhost:9358/gameserver" -H "accept: application/json"
```
4. Notice that health check is still enabled (formatted the output for readability)
```
{
  "object_meta": {
    ...
  },
  "spec": {
    "health": {
      "period_seconds": 3,
      "failure_threshold": 5,
      "initial_delay_seconds": 10
    }
  },
  "status": {
    ...
  }
}
```

**Anything else we need to know?**:
Reproduced on versions above 1.3.0 (did not test RCs).

**Environment**:
- Agones version: 1.5.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
- Troubleshooting guide log(s):
- Others:
