### ISSUE TITLE
connet gameserver after edit fleet

### ISSUE THREAD

**Issue by hulong121** [googleforgames/agones#1553]
**What happened**:
i'm trying to create a fleet follow this doc https://agones.dev/site/docs/getting-started/create-fleet/
every thing is ok before this step "Deploy a new version of the GameServer on the Fleet"
but after i run this command "kubectl edit fleet simple-udp", i can't connect to any gameserver

**What you expected to happen**:
maybe i can't connect to the old gameserver(container port 7654),
but those new allocated gameserver(container port 6000) still can't be connected, i think these new gameservers should be connected successfully.

**How to reproduce it (as minimally and precisely as possible)**:
just follow this guide https://agones.dev/site/docs/getting-started/create-fleet/ , until  excute "kubectl edit fleet simple-udp", wait for some seconds, then allocate gameserver with this command "kubectl create -f https://raw.githubusercontent.com/googleforgames/agones/release-1.5.0/examples/simple-udp/gameserverallocation.yaml -o yaml", after allocated success, connect to the gameserver with "nc -u {ip} {port}"

**Anything else we need to know?**:
i tried to delete the old gameserver, then i describe all gameserver with "kubectl describe gs", all those gameserver's container port is 6000, but i still can't connect to any gameserver.

**Environment**:
- Agones version: 1.5
- Kubernetes version (use `kubectl version`):1.14
- Cloud provider or hardware configuration:google cloud compute engine, ubuntu 18.0.4LTS, minikube
- Install method (yaml/helm):yaml
- Troubleshooting guide log(s):
- Others:

**Comment by aLekSer** [comment]
Actually there is an issue in documentation, not a bug in production. We can update both `ContainerPort` and use `ENV` variable `port` for `simple-udp` so that you can still connect to it.

**Comment by aLekSer** [comment]
Reading the documents one more time. There is a note on this:
```
Warning
This will make it such that you can no longer connect to the simple-udp game server.
```
I think we can close this ticket.
If you want to still be able to connect please add `args` or `env`
```
            args:
              - "-port=6000"
``` 
fields to the config yaml :

<details>
  <summary>Fleet.yaml</summary>

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-udp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      ports:
      - name: default
        containerPort: 6001
      template:
        spec:
          containers:
          - name: simple-udp
            image: gcr.io/agones-images/udp-server:0.21
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
            args:
              - "-port=6000"
```

</details>
