### ISSUE TITLE
Besides hostPort, can it be accessed in other ways?HostPort is dynamically changed.

### ISSUE THREAD

**Issue by sun-wenming** [googleforgames/agones#1631]
**What happened**:
Besides hostPort, can it be accessed in other ways?

**What you expected to happen**:

HostPort is dynamically changed.How can I access agones' gameserver through a fixed port?

I am a newer, this answer is very important to me

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.6.0
- Kubernetes version (use `kubectl version`): 1.15.0
- Cloud provider or hardware configuration:
- Install method (yaml/helm):helm
- Troubleshooting guide log(s):
- Others:

**Comment by sun-wenming** [comment]
I am try can resolve by service->nodePort. It is can use a fixed port to access.
Is there any cool way to reslove?

**Comment by markmandel** [comment]
I'm sorry, I'm not sure I 100% understand the question you are asking.

Have you gone through https://agones.dev/site/docs/getting-started/ ?

**Comment by sun-wenming** [comment]
This is maybe exact question: 
## I want a fixed port.

I have gone started. 
Like this -> https://agones.dev/site/docs/getting-started/create-gameserver/#3-connect-to-the-gameserver

`nc -u {IP} {PORT}`
This {IP} is host ip and this {PORT} will changed with gameserver restart.  

Now use k8s create nodePort service to targetPort ` 7654 ` .
I am not sure that is right. 

I can access the gameserver through a custom fixed port with  `fleet-svc.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: simple-tcp-svc
spec:
  type: NodePort
  selector:
    app: simple-tcp
  ports:
    - protocol: TCP
      name: simple-tcp-svc
      nodePort: 35555
      port: 7654
      targetPort: 7654
```
