### ISSUE TITLE
Fleet RollingUpdate with ImagePullBackoff and CPU Requests up to capacity: scaling down not active GameServerSet stuck

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1636]
There is an issue when we use up to 99% of all nodes capacities. 
If we use Fleet with smaller Replicas count, `Replicas = 10` for example, there is no such bug.

Use RollingUpdate scheduling strategy.
If there is an issue on initial `Fleet.yaml` configuration, and the wrong image is used. Then after fixing an image, Fleet would never self-heal, in terms it would never reach the desired amount of Replicas.

**What happened**:
Use default node pool consisting of 14 nodes. Bug would be reproducible with smaller cluster (need to correct Replicas accordingly)
```
default | OK | 1.15.12-gke.2 | 14 | n1-standard-4
```

Two GameServerSets was created:
One with 0 `Ready` and 1000 `Spec.Replicas`
And the second with 250 (25%) Ready and 250 in `Spec.Replicas`

**What you expected to happen**:
Fleet would have 1000 Ready Replicas after Update.
Old `GameServerSet` would be down scaled Gradually.

I expect that first invalid (not active) GameServerSet should update its Spec.Replicas parameter even though no GameServers was created in it. You can take a look here:
https://github.com/googleforgames/agones/blob/64754045608cccbea098bc3c98f0a648d0abcb49/pkg/fleets/controller.go#L478

**How to reproduce it (as minimally and precisely as possible)**:

1. Create the fleet with 1000 GameServers but wrong Image (see below):
2. Update the image to normal `image: gcr.io/agones-images/udp-server:0.21`
3.
```
kubectl get gameserversets
NAME               SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
simple-udp-22wmj   Packed       1000      1000      0           0       14m
simple-udp-zpnht   Packed       250       250       0           250     13m
```
4. As a side affect `kubectl delete fleet simple-udp` would leave 250 dangling GameServers.

**Anything else we need to know?**:
```
kubectl delete fleet simple-udp
kubectl apply -f ./fleet.yaml
```
Could be used as a workaround. But I expect that there should be a way to do this with Update of a Fleet.

**Environment**:
- Agones version: 1.6
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
`fleet.yaml`:
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-udp
spec:
  replicas: 1000
  template:
    spec:
      ports:
      - name: default
        containerPort: 7654
      template:
        spec:
          containers:
          - name: simple-udp
            image: gcr.io/agones-images/udp-server:1
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
```

```
Spec:
  Replicas:    1000
  Scheduling:  Packed
  Strategy:
    Rolling Update:
      Max Surge:        25%
      Max Unavailable:  25%
    Type:               RollingUpdate
```
