### ISSUE TITLE
Healthcheck failed: Connection refused. 

### ISSUE THREAD

**Issue by jicowan** [googleforgames/agones#1761]
**What happened**:
I seem to be having an issue similar #1313 except that 2 of the 5 game servers in my fleet are still running.  The rest were terminated and the fleet replicas were reduced to 2 automatically.  The logs indicate that the health check was failing before the game server was terminated, e.g. the SDK sidecar had the following error: 
```
2020-08-18T22:29:07.344876408Z {"error":"http: Server closed","gsKey":"default/stk-fleet-8kz9k-m65jr","message":"Health check: http server closed","severity":"error","source":"*sdkserver.SDKServer","time":"2020-08-18T22:29:07.34477809Z"}
```
and my game server had the following error: 
```
Failed to connect to localhost port 9358: Connection refused
```
I see the following in the logs of the 2 game servers that are still running: 
```
2020-08-18T23:07:52.063566636Z {"failureCount":1,"gsKey":"default/stk-fleet-2q4w6-g86cb","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2020-08-18T23:07:52.063410345Z"}
```

I don't see conflicting ports on the instance: 
```
tcp        0      0 127.0.0.1:50051         0.0.0.0:*               LISTEN      5901/./aws-k8s-agen 
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      4726/kubelet        
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      5701/kube-proxy     
tcp        0      0 127.0.0.1:61679         0.0.0.0:*               LISTEN      5901/./aws-k8s-agen 
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      3326/rpcbind        
tcp        0      0 127.0.0.1:45813         0.0.0.0:*               LISTEN      4726/kubelet        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      4395/sshd           
tcp        0      0 127.0.0.1:38489         0.0.0.0:*               LISTEN      3824/containerd     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      3957/master         
tcp6       0      0 :::32227                :::*                    LISTEN      5701/kube-proxy     
tcp6       0      0 :::10250                :::*                    LISTEN      4726/kubelet        
tcp6       0      0 :::61678                :::*                    LISTEN      5901/./aws-k8s-agen 
tcp6       0      0 :::111                  :::*                    LISTEN      3326/rpcbind        
tcp6       0      0 :::10256                :::*                    LISTEN      5701/kube-proxy     
tcp6       0      0 :::30289                :::*                    LISTEN      5701/kube-proxy     
tcp6       0      0 :::22                   :::*                    LISTEN      4395/sshd 
```
**What you expected to happen**:
I expect all the game servers to start and report as healthy

**How to reproduce it (as minimally and precisely as possible)**:
```
kind: Fleet
apiVersion: agones.dev/v1
metadata:
  annotations:
    agones.dev/sdk-version: 1.7.0
  creationTimestamp: '2020-08-18T22:52:49Z'
  generation: 5
  name: stk-fleet
  namespace: default
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stk
    spec:
      health: {}
      ports:
        - containerPort: 8080
          name: default
          portPolicy: Dynamic
      sdkServer: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - command:
                - /start.sh
              env:
                - name: WAIT_TO_PLAYERS
                  value: '120'
                - name: FREQ_CHECK_SESSION
                  value: '10'
                - name: NUM_IDLE_SESSION
                  value: '5'
                - name: SHARED_FOLDER
                  value: /sharedata
                - name: WAIT_TO_PLAYERS
                  value: '120'
                - name: GAME_SERVER_GROUP_NAME
                  value: agones-game-servers
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              image: .../stk:0.3'
              imagePullPolicy: Always
              lifecycle:
                preStop:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - /pre-stop.sh
              name: stk
              resources: {}
          nodeSelector:
            role: game-servers
          tolerations:
            - effect: NoExecute
              key: agones.dev/game-servers
              operator: Equal
              value: 'true'
          volumes:
            - emptyDir: {}
              name: shared-data
```

**Anything else we need to know?**:
Calling health check using the REST API, e.g. 
```
curl -d "{}" -H "Content-Type: application/json" -X POST http://localhost:${AGONES_SDK_HTTP_PORT}/health
Reserve 
```

**Environment**:
- Agones version: 1.8
- Kubernetes version (use `kubectl version`): 1.16
- Cloud provider or hardware configuration: AWS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
