### ISSUE TITLE
GameServerTemplate validation: no description when used big port values

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#1770]
**What happened**:
Inconsistent error message when using a big value for `grpcPort` field  `grpcPort: 33332229357`.
```
The Fleet "" is invalid
```

**What you expected to happen**:
Consistent error message without dependency on port field length.

**How to reproduce it (as minimally and precisely as possible)**:

Change `example/fleet.yaml` lines starting from 65 to :
```
      sdkServer:
        # sdkServer log level parameter has three options:
        #  - "Info" (default) The SDK server will output all messages except for debug messages
        #  - "Debug" The SDK server will output all messages including debug messages
        #  - "Error" The SDK server will only output error messages
        logLevel: Info
        grpcPort: 33332229357
        httpPort: 9358
```
`kubectl apply -f ` resulted fleet:
```
The Fleet "" is invalid
```

Do the same with smaller grpcPort value `2229357`:
```
spec.template.spec.sdkServer.grpcPort in body should be less than or equal to 65535
```
**Anything else we need to know?**:

**Environment**:
- Agones version:  1.8 (master)
- Kubernetes version (use `kubectl version`): 1.15
- Cloud provider or hardware configuration:
- Install method (yaml/helm): Terraform Helm
- Troubleshooting guide log(s):
- Others:
