### ISSUE TITLE
Helm setting the annotation of controller and allocator

### ISSUE THREAD

**Issue by 8398a7** [googleforgames/agones#1848]
**Is your feature request related to a problem? Please describe.**

I want to set the annotation of the controller/allocator pod.
This is because we need to add values to annotation when we get metrics in datadog.

```yaml
# (...)
metadata:
    #(...)
    annotations:
        ad.datadoghq.com/<CONTAINER_IDENTIFIER>.check_names: |
            ["openmetrics"]
        ad.datadoghq.com/<CONTAINER_IDENTIFIER>.init_configs: |
            [{}]
        ad.datadoghq.com/<CONTAINER_IDENTIFIER>.instances: |
            [
              {
                "prometheus_url": "http://%%host%%:%%port%%/<PROMETHEUS_ENDPOINT> ",
                "namespace": "<METRICS_NAMESPACE_PREFIX_FOR_DATADOG>",
                "metrics": [{"<METRIC_TO_FETCH>":"<NEW_METRIC_NAME>"}]
              }
            ]
spec:
    containers:
        - name: '<CONTAINER_IDENTIFIER>'
```

refs: https://docs.datadoghq.com/agent/kubernetes/prometheus/

**Describe the solution you'd like**

I would like to be able to inject annotations in values.yaml

**Describe alternatives you've considered**

Download the chart and rewrite it in parts.
However, this is less maintainable in the long run.

**Additional context**

None
