### ISSUE TITLE
Move to multiple dynamic range ports

### ISSUE THREAD

**Issue by WeetA34** [googleforgames/agones#1911]
Hi Mark,

Our game server uses 4 passthrough ports:
- 1 game port
- 3 tools ports
I would like to have the game port opened to the whole universe but not the 3 tools ports for which i want to allow only some sources

Proposal:
I imagine we can move port range (gameservers.minPort and gameservers.maxPort) to a list of port ranges and choose the port range to use in the game server ports definition.
So, we can define a different firewall rule for each range.

ie.
install values:
```
...
gameservers:
  namespaces: ["default"]
  ranges:
  - name: game
    minPort: 7000
    maxPort: 7099
  - name: tools
    minPort: 7100
    maxPort: 7199
```

and gamerserver definition:
```
apiVersion: "agones.dev/v1"
kind: GameServer
...
spec:
  # if there is more than one container, specify which one is the game server
  container: example-server
  # Array of ports that can be exposed as direct connections to the game server container
  ports:
  - name: default
    range: game
    portPolicy: Passthrough
    protocol: UDP
  - name: tool1
    range: tools
    portPolicy: Passthrough
    protocol: TCP
  - name: tool2
    range: tools
    portPolicy: Passthrough
    protocol: TCP
  - name: tool3
    range: tools
    portPolicy: Passthrough
    protocol: TCP
...
```

Workaround:
If the game port is UDP and Tools ports are TCP, you can only filter sources for TCP destinations.
But it's not possible if you want to apply different firewall rules for the same protocol

Thank you
Regards
Stéphane

**Comment by markmandel** [comment]
Interesting!

Curious - I assume the systems that are connecting on the "tooling" ports are running outside the cluster that your game servers are running on?

So some kind of scraping/pulling system for each game server?

Is that correct?

**Comment by WeetA34** [comment]
Hi Mark,

For now, these ports are mainly used for debugging purpose and must be filtered to only get access from our network.

Regards

**Comment by markmandel** [comment]
> For now, these ports are mainly used for debugging purpose and must be filtered to only get access from our network.

Understood - I'm just wondering what the connection pattern is. If we can pull the tooling into the same cluster as the game servers (or maybe run some kind of `kubectl` based tunnelling, if it's at development time only), then the problem might be solveable another way.

**Comment by WeetA34** [comment]
In fact, developers don't have access to the cluster. Right now, game servers are in Gamelift.
I'm not sure they can easily work with kubectl port forward for remote imgui and other tool like their inter process connect tool and debug draw infos which are pulled directly from the client.
If we don't want to change their work flow if we move to Agones, we should be able to access these ports directly without any tunneling tricks.

**Comment by markmandel** [comment]
Right - you would want to setup some kind of VPC to an internal corporate network type situation so you could lock down access to your specific network.

I'm guessing this would also be for both for development, but then also for production debugging?

**Comment by WeetA34** [comment]
We perform filtering with security group. Connection is from our internal network to these gameserver tools ports.
Yep, it's for development for sure and for production if the issue can't be reproduce in a development deployment.

**Comment by roberthbailey** [comment]
@markmandel - assuming that we did want to do this, is there a way to do it that is backwards compatible?

**Comment by markmandel** [comment]
> @markmandel - assuming that we did want to do this, is there a way to do it that is backwards compatible?

Probably have the helm configured range be the default range, and then have an ability like above to be able to configure extra ranges for each port. The things would be backward compatible.

It might be good to have a set of port ranges configured thought from the beginning (new CRD? Or new helm config?), rather than allowing any game server to specify any range they want -- it would be tricky to track an arbitrary range per GameServer.

**Comment by WeetA34** [comment]
It's probably more complicated (or at least longer) than the one hour video you did for moving gameservers from one port to multi-ports @markmandel 😄

I guess you can keep helm gameservers.minPort and gameservers.maxPort values for backward compatibility and assign them to a "default" range in the range list.
This "default" range would be used in gameserver definition if range is not set.

**Comment by WeetA34** [comment]
> It might be good to have a set of port ranges configured thought from the beginning (new CRD? Or new helm config?), rather than allowing any game server to specify any range they want -- it would be tricky to track an arbitrary range per GameServer.

Yep, that's my proposal: having a set of port ranges

**Comment by markmandel** [comment]
Not sure I like helm for this, because the config layer is hard to define/validate - but I don't think 

I would probably have something like:

```yaml
gameservers:
  minPort: 7000
  maxPort: 7000
  alternatePortRanges:
    - name: debug
      min: 1000
      max: 2000
    - name: health
      min: 4000
      max: 5000
```

Not quite sold on "alternatePortRanges" as a name, but you get the drift. "namedPortRanges" ? 

Which is similar to what you have above - but `gameservers.minPort` and `gameServers.maxPort` remain the default (and `default` would be a keyword name for non-assigned ports in the GameServer.

So we could validate them, and ensure there are no overlapping port ranges, as well as maintaining backward compatibility.

If there are no overlapping ranges, this also means you could have one [PortAllocator](https://github.com/googleforgames/agones/blob/master/pkg/gameservers/portallocator.go) per range name, and it becomes quite easy to manage.

Then we could do the same as you have above, where you assign the port range by name.

Howzat?

**Comment by WeetA34** [comment]
Hi Mark,
i don't know if you were waiting something else from me.
You're proposal sounds good.
Thank you

**Comment by markmandel** [comment]
@WeetA34 not waiting on anything, just prioritising other work.

Since this is of import to you, would you be interested in working on it?

**Comment by WeetA34** [comment]
No problem Mark. It doesn't seem to be a feature tons of person are interested on :)
We're not in a hurry at the moment.
To be honest, i don't think i have the proper dev skill level to work on it :)

**Comment by markmandel** [comment]
Come join us in #development in Slack, we'll get you leveled up! 😎

**Comment by WilSimpson** [comment]
I'm going to start working on this. This is my first time using Helm, but this is what I researched and came up with.

It looks like the current min/max port are passed as [environment variables](https://github.com/googleforgames/agones/blob/main/install/helm/agones/templates/controller.yaml#L79) to the [controller](https://github.com/WilSimpson/agones/blob/main/cmd/controller/main.go#L272). Following Mark's schema, I was thinking of using a [helm loop](https://github.com/WilSimpson/agones/blob/main/cmd/controller/main.go#L272) to set a string encoded environment variable with commas separating the values and semicolons separating the tuples. So the above example would become `debug,1000,2000;health,4000,5000`.

Please let me know if you think there are any better approaches!

**Comment by WeetA34** [comment]
Hello @WilSimpson
When i checked how to handle this, i found the same conclusion.
I was thinking of using an extra environment variable EXTRA_PORT_RANGES (ie) with the following format:
<NAME>:<MIN>:<MAX>.
Multiple port ranges separated by commas.
ie: tools:5000:5999,whatever:6000:6999

**Comment by WeetA34** [comment]
Then first thing is port ranges checks, ensure:
- that for each extra port ranges, min is less than max
- there is no overlapping port ranges (between each extra port range and between any of extra port range and min/max)

**Comment by markmandel** [comment]
> Hello @WilSimpson
> When i checked how to handle this, i arrived to the same conclusion.
> I was thinking of using an extra environment variable EXTRA_PORT_RANGES (ie) with the following format:
> `<PORT_RANGE_NAME>:<PORT_RANGE_MIN>:<PORT_RANGE_MAX>`.
> And multiple port ranges separated by commas: (ie: `tools:5000:5999,whatever:6000:6999`)

I like this one 👍🏻 

But yeah - that's an excellent point, I hadn't considered how to pass it to the controller. Comma delimited list seems like a legit way to go.

As a possible other suggestion: Use a URL query param encoded list (there are built in parsers already, that's why we use it on Feature Flags), but then you still have to work out how to specify min/max on it 🤔 

`EXTRA_PORT_RANGES="tools=5000%3A6000&whatever=7000%3A9000"`

Would still need to split on ":", but would at least take out some of the parsing pain? (although that %3A is... not... pretty 😬 maybe this is a bad idea).

**Comment by WilSimpson** [comment]
I was thinking how they are encoded is less important because they will be set with a `helm set` or `helm -f`. If used with `helm set` then it would become `helm ... --set gameserver.alternatePortRanges [{name: "debug", min: "1000", max: "2000"}, {name: "health", min: "4000", max: "5000"}]`. Then in the case of `helm -f` you would just specify a `yaml` file with 
```yaml
gameservers:
  alternatePortRanges:
    - name: debug
      min: 1000
      max: 2000
    - name: health
      min: 4000
      max: 5000
```

The reason I chose comma was arbitrary, but I do like semicolon better and that's a simple change. The reason I chose `\n` was because it's a natural conversion with helm range loop:
```yaml
{{- if  .Values.gameserver.altPortRanges }}
- name: ALT_PORTS
  value: |-
  {{- range .Values.gameserver.altPortRanges }}
  - {{ printf "%s:%d:%d" .name .min .max }}
  {{- end }}
{{- end }}
```
