### ISSUE TITLE
Fleet Autoscaler - Fleet name CRD Validation issue

### ISSUE THREAD

**Issue by manleydev** [googleforgames/agones#1954]
**What happened**:

A fleet named `game-1.0.0.0` can be created, but the fleet auto scaler cannot reference the fleet name `game-1.0.0.0` because a validation error at the CRD level.

**What you expected to happen**:

Preferably, the auto scaler should be able to able to reference the fleet.

**How to reproduce it (as minimally and precisely as possible)**:

Create a fleet named `game-1.0.0.0` then attempt to create a simple auto scaler for that fleet.

**Anything else we need to know?**:

Section found by Daniel: https://github.com/googleforgames/agones/blob/master/install/helm/agones/templates/crds/fleetautoscaler.yaml#L54

**Environment**:
- Agones version: v1.11.0
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: Azure AKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):

```
Error: failed to create resource: FleetAutoscaler.autoscaling.agones.dev "fleet-scaler" is invalid: spec.fleetName: Invalid value: "": spec.fleetName in body should match '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
```

```
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-scaler
spec:
  fleetName: fleet-1.0.0.0
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 1
      maxReplicas: 20
```
