### ISSUE TITLE
Cannot connect to a game server using Docker Desktop (with integrated K8s cluster or Minikube)

### ISSUE THREAD

**Issue by panicq** [googleforgames/agones#1990]
**What happened:**

I installed Agones using helm on the K8s cluster delivered with Docker Desktop (windows, using WLS2). My goal is to be able to test a local cluster on my dev machine (so no cloud).
I was able to integrate the SDK and start a game server correctly. I have the logs of the server and can see that the SDK is working. When I **kubectl get gs** I can see an **IP** and **port** and that the server status is **READY**

**Unfortunately I cannot connect to this IP/Port from my game client (outside the cluster).**

**What you expected to happen:**

To connect from my game client using the given ip/port (from a simple **kubectl get gs**).

**How to reproduce it (as minimally and precisely as possible):**
Install agones on docker desktop (WLS2) and follow the game server documentation page:
https://agones.dev/site/docs/getting-started/create-gameserver/
Or use your own server.

**Anything else we need to know?:**

Here is what I tried:
- Connecting using host.docker.internal
- Using minikube I was able to get to the same point on this cluster. I also tried connecting using the **minkube ip**
- Starting the nodejs example from the website -> Failed to resolve ip/port...

Note that I'm able to connect to a standard UDP Loadbalancer Service with docker desktop, so in that case the IP/Port of the service is correctly exposed.

Environment: Local
Agones version: agones.dev/v1
Kubernetes version 1.19
Install method (yaml/helm): helm
Others: Docker Desktop on Windows with WLS2

**Comment by markmandel** [comment]
A not too shabby workaround if you are on Windows and the multiple layers of virtualistion make it hard to get a direct connection - you could create a Service just for local development to point to a specific GameServer instance, like so, basically to act as a traffic tunnel for local development:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: agones-gameserver
spec:
  type: LoadBalancer
  selector:
    agones.dev/gameserver: ${GAMESERVER_NAME}
  ports:
  - protocol: UDP
    port: 7000 # local port
    targetPort: ${GAMESERVER_CONTAINER_PORT}
```

If you want to connect to a different `GameServer`, `kubectl edit agones-gameserver` and edit the `${GAMESERVER_NAME}` value to point to the new `GameServer` instance and/or the `${GAMESERVER_CONTAINER_PORT}` value, if it had changed (most likely it probably won't I expect).
