### ISSUE TITLE
Configurable maximum time without allocation (and shutdown after that time)

### ISSUE THREAD

**Issue by pgilfillan** [googleforgames/agones#2031]
**Is your feature request related to a problem? Please describe.**

This is related to #1782 in that we want a way to reduce costs by not having a large number of idle servers. During development images are pushed all the time and it would be prohibitively expensive to have fleets for every single image tag/version. The reason that the other issue I think doesn't quite fit our use case is that we aren't ever completely sure which version will be needed by a team, and when they'll need it, and so it's hard to know when to set the replicas to 1 or 0.

Our current solution to this is when a match is formed with our matchmaker we try to allocate to a fleet with the correct version using the `matchLabels` functionality of `GameServerAllocation`. If there's no existing fleet, but there is a matching image in our repository, the service will create a single GameServer object for the client to join once it spins up. The game server has logic to shutdown if no one ends up joining it, to avoid dangling pods.

The problem with this approach is if that shutdown logic somehow fails then you end up with the dangling pod. It's also just not very "clean", having to implement the shutdown logic inside the game server.

**Describe the solution you'd like**

Would it be possible to configure the maximum amount of time a GameServer can spend not Allocated? Maximum amount of time spent Ready is the obvious state, but I suppose it could also apply to Scheduled, Reserved and RequestReady. I imagine this would work the same as the health configuration, something like:

```
maxTimeBeforeAllocation:
  enabled: false # Enable or disable
  initialDelaySeconds: 5 # Initial delay (might not be needed, could just be part of periodSeconds)
  periodSeconds: 300 # Number of seconds spent unallocated before the server is shutdown
```

**Describe alternatives you've considered**

- Our current implementation isn't awful and has only left a couple of dangling servers, so we could just stick with what we've got. But it would be nice to be cleaner, and this functionality might be useful for others.
- We could have a CronJob that watches for old servers and deletes them. This would involve writing the code for it, adding CI to make the image, managing the deployment etc. Plus it's 1 extra pod. So possible but more work.
