### ISSUE TITLE
Azure aks TCP connections

### ISSUE THREAD

**Issue by g3gurung** [googleforgames/agones#2098]
I have successfully created a UDP inbound rule via azure NSG and everything works with the game servers following this [documentation](https://agones.dev/site/docs/installation/creating-cluster/aks/), but now I am trying to do the same for TCP connection with the inbound rule via NSG. I also changed the game servers to listen from UDP to TCP connections but now I can't connect with TCP to the gameservers.

Is there something I am missing?

**Comment by g3gurung** [comment]
My fleet yaml was missing **protocol: TCP** ... after I added it worked... XD

```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: game-server
spec:
  replicas: 2
  template:
    spec:
      ports:
      - name: default
        containerPort: 7456
        protocol: TCP #this needed to be added
      template:
        spec:
          containers:
          - name: game-server
            image: image_uri
            env: 
            # Disables the UDP listener (Enabled by default)
            - name: "UDP"
              value: "FALSE"
            # Enables the TCP listener (Disabled by default)
            - name: "TCP"
              value: "TRUE"
              ...
```
