### ISSUE TITLE
Failure after defining a second container to a Fleet file

### ISSUE THREAD

**Issue by blancsys** [googleforgames/agones#2131]
**What happened**:

I have created a Helm Chart that defines a Fleet. It's up and running. When it's deployed, each pod has 2 containers (the game and the sidecar container injected by Agones). So far so good. 

Now, we need to add a third container to the pod for our own use (I mean, the new container is not directly related to Agones). So, I have changed the pod definition to add a second container but it doesn't work. The error I get is:

```admission webhook \"validations.agones.dev\" denied the request: Fleet configuration is invalid```

NOTE: I'm using FluxCD to deploy the Helm releases so maybe the Agones message is just the last part of the message.
 
**What you expected to happen**:

I expect to see the Helm release deployed, creating pods with 3 containers (the game, the Agones sidecar and our sidecar container)

**How to reproduce it (as minimally and precisely as possible)**:

This is the Fleet configuration (I have removed the parts that doesn't apply and I have obfuscated the images):

```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: my-name
spec:
  [...]
  template:
    [...]
    spec:
      [...]
      template:
        spec:
          containers:
          - name: game
            image: <game-image>
          - name: agent                          # <-- These two lines are problematic
            image: <agent-image>                 # <-- These two lines are problematic
```

**Anything else we need to know?**:

As I said, if you remove the last two lines above, everything works as expected. So, it seems like Fleet is not happy with the addition of the second container. Adding a second container is supported, according to what I [read here](https://agones.dev/site/docs/reference/gameserver/)

**Environment**:

- Agones version: 1.14.
- Kubernetes version (use `kubectl version`): 1.20.7
- Cloud provider or hardware configuration: On-prem Kubernetes cluster
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s): "admission webhook \"validations.agones.dev\" denied the request: Fleet configuration is invalid"
- Others:

Any feedback is welcome.

Thanks!

**Comment by blancsys** [comment]
I found the problem, this is not a bug. So, I need to add the "container" field to indicate which container runs the game:

```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: my-name
spec:
  [...]
  template:
    [...]
    spec:
      container: game      # <--- Added this line
      [...]
      template:
        spec:
          containers:
          - name: game
            image: <game-image>
          - name: agent                   
            image: <agent-image>   
```

Closing this issue.
