### ISSUE TITLE
Prometheus metrics: Use ServiceMonitor instead of deprecated annotation mechanism

### ISSUE THREAD

**Issue by zifter** [googleforgames/agones#2262]
**Is your feature request related to a problem? Please describe.**
I would like to export prometheus metrics in the latest versions of prometheus stack operator.
It's easy to export metrics from controller - create ServiceMonitor with relablings ([documentation is not complete about that](https://github.com/googleforgames/agones/blob/main/site/content/en/docs/Guides/metrics.md#backend-integrations))
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: agones-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: agones
spec:
  selector:
    matchLabels:
      agones.dev/role: controller
  endpoints:
    - port: web
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          targetLabel: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
```
But it's impossible to create ServiceMonitor for exporting allocator and ping metrics.

**Describe the solution you'd like**
According to [latest documentation](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md#prometheusioscrape) Prometheus is not supporting **prometheus.io/scrape** annotation anymore.
It's better to switch ServiceMonitor CRD and provide ready-to-use ServiceMonitor out of the box.

**Describe alternatives you've considered**
-

**Additional context**
-
