### ISSUE TITLE
Gameservers stuck on scheduled when initial delay is set too low

### ISSUE THREAD

**Issue by GeorgianaTurcsanyi** [googleforgames/agones#2266]
**What happened**:
This is more of a question/documentation request than a bug.

I am trying to deploy gameserver using Agones and I am having issues connecting to the SDK based on how the `initialDelaySeconds` is set in the healthcheck. When the value is set too low (60 seconds in the case of my gameserver), I get the following:

```
2021-09-16 13:39:34,594][DEBUG] Agones: Connecting...
[2021-09-16 13:39:34,595][INFO] Attempting to connect...1:

Attempting to connect...1

Curl error 7: Failed to connect to localhost port 9358: Connection refused

Curl error 7: Failed to connect to localhost port 9358: Connection refused

[2021-09-16 13:39:34,622][INFO] Agones SendRequest failed: /gameserver Cannot connect to destination host
```

Increasing the `initialDelaySeconds` makes this disappear,  but the errors on the sidecar side are very confusing and it took a lot of time for me to track the issue. This is what the sidecar in debug mode is showing when this issue is happening:

```
{"ctlConf":{"Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","GRPCPort":9357,"HTTPPort":9358},"featureGates":"CustomFasSyncInterval=false\u0026Example=true\u0026NodeExternalDNS=false\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026RollingUpdateOnReady=true\u0026SDKWatchSendOnExecute=true\u0026StateAllocationFilter=false","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2021-09-17T08:34:34.829374298Z","version":"1.17.0"}
{"gsKey":"game-servers/gds-example","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2021-09-17T08:34:34.860626263Z"}
{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2021-09-17T08:34:34.956395488Z"}
{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2021-09-17T08:34:34.956769083Z"}
{"gsKey":"game-servers/gds-example","health":{"periodSeconds":5,"failureThreshold":5,"initialDelaySeconds":30},"message":"Setting health configuration","severity":"debug","source":"*sdkserver.SDKServer","time":"2021-09-17T08:34:34.961409071Z"}
{"gsKey":"game-servers/gds-example","message":"Starting GameServer health checking","severity":"debug","source":"*sdkserver.SDKServer","time":"2021-09-17T08:34:34.961478151Z"}
{"gsKey":"game-servers/gds-example","message":"Starting SDKServer http health check...","severity":"debug","source":"*sdkserver.SDKServer","time":"2021-09-17T08:34:34.961487649Z"}
{"gsKey":"game-servers/gds-example","message":"Starting workers...","queue":"agones.dev.game-servers.gds-example","severity":"info","source":"*sdkserver.SDKServer","time":"2021-09-17T08:34:34.961498146Z","workers":1}
{"gsKey":"game-servers/gds-example","message":"Sending GameServer Event to connectedStreams","severity":"debug","source":"*sdkserver.SDKServer","time":"2021-09-17T08:35:04.881295075Z"}
{"failureCount":1,"gsKey":"game-servers/gds-example","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-09-17T08:35:09.962886019Z"}
{"failureCount":2,"gsKey":"game-servers/gds-example","message":"GameServer Health Check failed","severity":"warning","source":"*sdkserver.SDKServer","time":"2021-09-17T08:35:14.963250711Z"}
```

**What you expected to happen**:

A more verbose error in the sidecar or a clear way to figure that the SDK isn't initialised yet and ready for connection.

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: "gds-example" 
spec:
  container: example-server
  ports:
    - name: default
      portPolicy: Static
      container: test_gs
      containerPort: 23434
      hostPort: 23534
      # protocol being used. Defaults to UDP. TCP and TCPUDP are other options
      protocol: UDP
  # Health checking for the running game server
  health:
      initialDelaySeconds: 23
      periodSeconds: 5
      failureThreshold: 5
  sdkServer:
    logLevel: Debug
    grpcPort: 9357
    httpPort: 9358
  template:
    metadata:
      labels:
        myspeciallabel: test
    # Pod Specification
    spec:
      containers:
        - name: test_gs
          image:  [gameserver_image]
          imagePullPolicy: Always
```
**Anything else we need to know?**:

**Environment**:
- Agones version: 1.17
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: Local environment with minikube v1.23.0 on Ubuntu 20.04
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s):
- Others:
