### ISSUE TITLE
Stateful configuration in Fleet

### ISSUE THREAD

**Issue by scarlet25151** [googleforgames/agones#2273]
**Is your feature request related to a problem? Please describe.**
In some scenario, we need to expose some ports for gameserver's communication, this is some kind of stateful information in config or env, and we also want to use fleet to manage the autoscaling of that gameserver. Example below:

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: supertuxkart
spec:
  replicas: 10
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 8080
        # here we want for each replica assigned different ports
      - name: GATE
        containerPort: 10001
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: supertuxkart
            image: gcr.io/agones-images/supertuxkart-example:0.2
```
in the case above, we want assigned different port (GATE(replica 1): 10001, GATE: 10002, ... GATE: 10010) for each replica, but since fleet is stateless, we cannot do that. Since gameserver in fleet is stateless, we don't need the replica to be in a order, we just want to assigned different config to different replica

**Describe the solution you'd like**
While defining a fleet we can assigned a set of stateful information, which can be in a range.
``` yaml
spec:
...
  statefulConfig:
  - name: GATE_PORT
     type: number
     filePath: spec.ports["GATE"].containerPort
     startFrom: 10001
...
``` 
when apply the fleet, controller will use the index of replica and the `startFrom` to generate and inject the port to each replica configuration or enviroment.
**Describe alternatives you've considered**
Is there any other way to solve the problem like statefulset version fleet? 

**Additional context**

**Comment by roberthbailey** [comment]
Agones already has a way to assign unique ports to each game server in a fleet using the ports array in the [spec](https://agones.dev/site/docs/reference/gameserver/). 

If you use a dynamic port policy, then each game server will get a host port assigned to it. The ports won't be deterministic, but you will be able to discover them by inspecting the game server resources that are created by the fleet. 

If you do something like:

```yaml
spec:
  replicas: 10
  template:
    spec:
      ports:
      - name: external
        containerPort: 8080
      - name: GATE
        containerPort: 10001
```

then each game server will have 2 host ports allocated - you would use the port named "external" in your match maker to connect clients to the game server and the port named "GATE" to connect to your game server internally.

**Comment by roberthbailey** [comment]
> While defining a fleet we can assigned a set of stateful information, which can be in a range.

How do you see this stateful config being applied to the game server resource? Would it turn into the `containerPort` number? Would it be injected into the pod as an environment variable (so that the game server can bind to a specific port)?

One of the nice things about the hostPort -> containerPort mapping is that each container can internally bind to the same port number, and you can run multiple instances of that container on the same underlying machine. The container runtime then maps requests destined to the host port into the server inside the container on the container port.

**Comment by scarlet25151** [comment]
Appreciated a lot for your answers in detail, indeed the dynamic port policy in Gameserver can assigned different port to each game server. However, for my case it's a little bit different and there is something else need abilities like statefulset.
``` yaml
apiVersion: agones.dev/v1
        kind: Fleet
        metadata:
          name: logic-sample
        spec:
          replicas: 10
          template:
            metadata:
              labels:
               app: logic-sample
            spec:
              ports:
              - name: default
                portPolicy: Dynamic
                containerPort: 26000
              health:
                initialDelaySeconds: 30
                periodSeconds: 60
              # Parameters for game server sidecar
              sdkServer:
                logLevel: Info
                grpcPort: 9357
                httpPort: 9358
              # The GameServer's Pod template
              template:
                metadata:
                  labels:
                    app: logic-sample
                spec:
                  containers:
                  - name: sample
                    image: xxxxx
                    env:
                    - name: ZONE_ID
                      value: '10001'
                    - name: SQL_TABLE_NAME
                      value: 'tb_01'
                    - name: SCENE_PORT
                      value: '11001'
```
Like in the sample, we already implement dynamic port to ensure the different port for gameserver in a fleet. 

But in our gameserver container some other ports is used to connect to a scene server or ranking-system server, also the gameserver will connect to some SQL database's individual table. 

Since in Fleet all the env in container would be the same, it's become hard for us when we want to assigned gameserver with different tables' name (SQL_TABLE_NAME: 'tb_01' for gs1, SQL_TABLE_NAME: 'tb_02' for gs2...) and using different port to connect to other system's component (SCENE_PORT:11001 for gs1, SCENE_PORT:11002 for gs2...). 

We know in statefulset, as the pod is in some order by name, we can assigned the env by convert their pods name, and when we consider gamesever is different in a fleet, is there some way to deal with that?

> > While defining a fleet we can assigned a set of stateful information, which can be in a range.
> 
> How do you see this stateful config being applied to the game server resource? Would it turn into the `containerPort` number? Would it be injected into the pod as an environment variable (so that the game server can bind to a specific port)?
> 
> One of the nice things about the hostPort -> containerPort mapping is that each container can internally bind to the same port number, and you can run multiple instances of that container on the same underlying machine. The container runtime then maps requests destined to the host port into the server inside the container on the container port.
