### ISSUE TITLE
Feature Gate "RollingUpdateOnReady" is not a valid Feature Gate in Agones Sidecar

### ISSUE THREAD

**Issue by Shazambom** [googleforgames/agones#2307]
**What happened**:
Panic on agones sidecar when deployed using helm. Error code is: **Feature Gate "RollingUpdateOnReady" is not a valid Feature Gate**

full stack trace for sidecar: 
```
goroutine 1 [running]:
agones.dev/agones/pkg/util/runtime.Must(...)
        /go/src/agones.dev/agones/pkg/util/runtime/runtime.go:70
main.parseEnvFlags(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/agones.dev/agones/cmd/sdk-server/main.go:294 +0x11e5
main.main()
        /go/src/agones.dev/agones/cmd/sdk-server/main.go:71 +0x65

```

**What you expected to happen**:
Expected a healthy deployment of the sidecar

**How to reproduce it (as minimally and precisely as possible)**:
using largely the default helm deployment method:

```
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: pong
spec:
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
```

**Anything else we need to know?**:
Using an M1 Mac so using the ARM image is necessary.
It appears as though the flag `RollingUpdateOnReady` is missing in `agones/pkg/util/runtime/features.go:61`

**Environment**:
- Agones version: 1.18.0-70d56ad-linux_amd64
(`docker pull gcr.io/agones-images/agones-sdk:1.18.0-70d56ad-linux_amd64`)
- Kubernetes version (use `kubectl version`): v1.22.2
- Cloud provider or hardware configuration: aws
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others: Using an M1 Mac so using the ARM image is necessary. This is deployed locally using minikube. Here is my helm install command: `helm install my-release -n agones-system agones/agones --set "gameservers.namespaces={default,pong-dev}" --create-namespace --set "agones.image.sdk.tag=1.18.0-70d56ad-linux_amd64"`
