### ISSUE TITLE
TCPUDP not supported

### ISSUE THREAD

**Issue by stpnov** [googleforgames/agones#2314]
**What happened**:

Pod "gameserver" is invalid: spec.containers[0].ports[0].protocol: Unsupported value: "TCPUDP": supported values: "SCTP", "TCP", "UDP"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: agones.dev/v1
kind: GameServer
spec:
  ports:
     portPolicy: Static
     containerPort: 7000
     hostPort: 7000
     protocol: TCPUDP
```

**Anything else we need to know?**:

**Environment**:
- Agones version: v1.18.0
- Kubernetes version (use `kubectl version`): v1.22.1
- Install method (yaml/helm): helm
