### ISSUE TITLE
allow passing certificates as values instead of files in the Helm chart

### ISSUE THREAD

**Issue by rahil-p** [googleforgames/agones#2364]
**Problem**

For some manifests, certificates are read in from the `certs` directory.  This makes it very inconvenient for a user to supply their own certificates.   Here's an example from the `allocator-tls` secret:

```yaml
data:
{{- if .Values.agones.allocator.generateTLS }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- else }}
  tls.crt: {{ .Files.Get "certs/allocator/server.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/allocator/server.key" | b64enc }}
{{- end }}
```

**Solution**

This problem could be solved by exposing values for providing certificate data.  Using the example above:

```yaml
data:
{{- if .Values.agones.allocator.generateTLS }}
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
{{- else }}
  tls.crt: {{ default (.Files.Get "certs/allocator/server.crt") .Values.agones.allocator.tlsCrt | b64enc }}
  tls.key: {{ default (.Files.Get "certs/allocator/server.key") .Values.agones.allocator.tlsKey | b64enc }}
{{- end }}
```

The user could supply the certificate and key with:

```sh
helm install my-release agones/agones \
  --set-file agones.allocator.tlsCrt=mydir/tls.crt,agones.allocator.tlsKey=mydir/tls.key
```
