### ISSUE TITLE
Is there any purpose for not supporting the updating of Gameserver?

### ISSUE THREAD

**Issue by scarlet25151** [googleforgames/agones#2371]
**Is your feature request related to a problem? Please describe.**

When I apply a single gameserver something like the example below, it success create a pod and everything goes well, 
```yaml
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  generateName: "simple-game-server-"
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7654
  template:
    spec:
      containers:
      - name: simple-game-server
        image: simple-game-server:0.5
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "64Mi"
            cpu: "20m"
```
But when I apply a new yaml or using `kubectl edit` in cli, **trying to modify or update the image version** to `simple-game-server:1.0` the spec in gameserver is changed but the pod of the server would not be killed and restart with the new image, when I tried to edit the spec in the pod directly my behavior is forbidden, something like this:
```bash
# pods "simple-game-server" was not valid: 
# * spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations) 
```
Also, when I delete pod, the gameserver would not start a new one.

I've look into the [GameServer Specification](https://agones.dev/site/docs/reference/gameserver/) and notice that:

> The GameServer resource does not support updates. If you need to make regular updates to the GameServer spec, consider using a Fleet.

**Describe the solution you'd like**

Now in my company, we can make sure that some game will use the policy _Stop the server and maintenance_
so there would be no player or the connection to the server when it's updating. another thing is that since my gameserver is connecting to an datatbase so if we use fleet for rolling updating, there may be 2 server connecting to 1 database and it may create inconsistent data

Therefore we would have a pattern that delete one old pod and start a new one with new image using gameserver rather than fleet.

**So I have some doubt on the design that why gameserver would not support update?** 

**Describe alternatives you've considered**

**Additional context**
