### ISSUE TITLE
Proposal: Variable buffer size based on Allocated status in FleetAutoscaler

### ISSUE THREAD

**Issue by yoshd** [googleforgames/agones#2379]
**Is your feature request related to a problem? Please describe.**

If the buffer size is a fixed length, it is difficult to optimize the cost when the increase or decrease in inflow is not constant.
For example, if the FleetAutoscaler buffer is set to a large value, it can handle a large influx, but if the influx is small, it will incur unnecessary costs.

**Describe the solution you'd like**

Proposal variable buffer size based on Allocated status in FleetAutoscaler.
This allows FleetAutoscaler to autoscale according to the actual load by minimizing the number of GameServer when the inflow is low, while increasing the scaling granularity when the inflow is high.

Configure FleetAutoscaler as follows:

```yaml
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler-example
spec:
  fleetName: fleet-example
  policy:
    type: VariableBuffer
    buffer:
      # Set the percentage based on the number of Allocated GameServers.
      # i.e. If the number of Allocated GameServers is 10 and the bufferSize is 30%, there will be 3 Ready instances.
      bufferSize: 30%
      # Same as `type: Buffer`
      minReplicas: 10
      # Same as `type: Buffer`
      maxReplicas: 20
```

**Describe alternatives you've considered**

I could build my own scaling logic with a Webhook Endpoint, but it would be labor intensive.
