### ISSUE TITLE
GameServerAllocation is not working for "High Density GameServers"

### ISSUE THREAD

**Issue by nncsang** [googleforgames/agones#2408]
**What happened**:
I followed the document "High Density GameServers" (at https://agones.dev/site/docs/integration-patterns/high-density-gameservers/) to run multiple concurrent game sessions in a single GameServer process.

I use Nodejs and the Nodejs SDK to implement the GameServer. The GameServer is implemented as follows:

```
const AgonesSDK = require('@google-cloud/agones-sdk');
const util = require('util');

const sleep = util.promisify(setTimeout);

const DEFAULT_TIMEOUT = 60;
const MAX_TIMEOUT = 2147483;

const connect = async () => {
	let agonesSDK = new AgonesSDK();

	let lifetimeInterval;
	let healthInterval;
	let serverName = ""
	
	try {
		console.log(`Connecting to the SDK server...`);
		await agonesSDK.connect();
		console.log('...connected to SDK server');
		

		let connectTime = Date.now();
		lifetimeInterval = setInterval(() => {
			let lifetimeSeconds = Math.floor((Date.now() - connectTime) / 1000);
			console.log(`Running for ${lifetimeSeconds} seconds`);
		}, 10000);
		healthInterval = setInterval(() => {
			agonesSDK.health();
			console.log('Health ping sent');
		}, 20000);


		agonesSDK.watchGameServer(async (result) => {
			let output = `GameServer Update:
	name: ${result.objectMeta.name}
	state: ${result.status.state}
	labels: ${result.objectMeta.labelsMap.join(' & ')}
	annotations: ${result.objectMeta.annotationsMap.join(' & ')}`;
			
			console.log(output);

			if (result.objectMeta.name == serverName && result.status.state == "Allocated" && output.indexOf("agones.dev/sdk-gs-session-ready,false") != -1){
				console.log("Set gs-session-ready to true")
				await agonesSDK.setLabel('gs-session-ready', "true");
			}
		}, (error) => {
			console.error('Watch ERROR', error);
			clearInterval(healthInterval);
			clearInterval(lifetimeInterval);
			process.exit(0);
		});

		await sleep(10000);
		console.log('Marking server as ready...');
		await agonesSDK.ready();

		let result = await agonesSDK.getGameServer();
		serverName = result.objectMeta.name;
		console.log('Server Info', result);

		await agonesSDK.setLabel('gs-session-ready', "false");

		result = await agonesSDK.getGameServer();
		console.log('Server Info', result);

		
		
		await sleep(864000 * 1000);
		console.log('Shutting down...');
		agonesSDK.shutdown();

		await sleep(10000);
		console.log('Closing connection to SDK server');
		clearInterval(healthInterval);
		agonesSDK.close();

		await sleep(10000);
		console.log('Exiting');
		clearInterval(lifetimeInterval);

		// Some parts of the SDK are still using the event loop so must exit manually until fixed
		process.exit(0);
	} catch (error) {
		console.error(error);
		clearInterval(healthInterval);
		clearInterval(lifetimeInterval);
		process.exit(0);
	}
};

connect()
```

I created a fleet as follows:
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: sang
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 26000
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: sgs
            image: gcr.io/sangs-space/sang-gs:0.0.9
```

I use the follow GameServerAllocation to allocate GameServer to my GameClient.
```
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: sang
        agones.dev/sdk-gs-session-ready: "true" # this is important
      gameServerState: Allocated # new state filter: allocate from Allocated servers
    - matchLabels:
        agones.dev/fleet: sang
      gameServerState: Ready # Allocate out of the Ready Pool (which would be default, so backward compatible)
  metadata:
    labels:
      agones.dev/sdk-gs-session-ready: "false" # this removes it from the pool
```
      
 At the beginning, there are two GameServer whose status are Ready
 
```
NAME               STATE       ADDRESS         PORT   NODE                                    AGE
sang-6dcxr-dzv4v   Ready       34.81.194.170   7773   gke-agones-default-pool-0284a633-vjjb   39m
sang-6dcxr-qp99d  Ready   34.81.194.170   7360   gke-agones-default-pool-0284a633-vjjb   39m
```

The first time that I used the GameServerAllocation to request an Allocation, one of the GameServer's status change to Allocated.

```
NAME               STATE       ADDRESS         PORT   NODE                                    AGE
sang-6dcxr-dzv4v   Ready   34.81.194.170   7773   gke-agones-default-pool-0284a633-vjjb   39m
sang-6dcxr-qp99d  Allocated   34.81.194.170   7360   gke-agones-default-pool-0284a633-vjjb   39m
```

Then, I doubled check the label 'agones.dev/sdk-gs-session-ready' of the GameServer sang-6dcxr-qp99d  is changed to true.

The second time I used the GameServerAllocation to request an Allocation, the Allocator Service did not return the GameServer sang-6dcxr-qp99d, but return the other GameServer, which is sang-6dcxr-dzv4v. Moreover, the status of sang-6dcxr-dzv4v is changed to Allocated

```
NAME               STATE       ADDRESS         PORT   NODE                                    AGE
sang-6dcxr-dzv4v   Allocated   34.81.194.170   7773   gke-agones-default-pool-0284a633-vjjb   39m
sang-6dcxr-qp99d  Allocated   34.81.194.170   7360   gke-agones-default-pool-0284a633-vjjb   39m
```

The third time  I used the GameServerAllocation to request an Allocation, the Allocator Service did not return any GameServers. Even though, both of the GameServer had 'agones.dev/sdk-gs-session-ready' set to true.
 
**What you expected to happen**:

- For the second call, the Allocator should return the GameServer sang-6dcxr-qp99d.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.9
- Kubernetes version (use `kubectl version`): 1.21.6-gke.1500
- Cloud provider or hardware configuration: GCP
- Install method (yaml/helm): yaml
- Troubleshooting guide log(s):
- Others:
