### ISSUE TITLE
If Fleet is allocated during a rolling update, the old GameServerSet may not be deleted

### ISSUE THREAD

**Issue by yoshd** [googleforgames/agones#2432]
**What happened**:

The logic for scaling down the current old GameServerSet may not complete the scaling down even after the scaling up is complete if there is a GameServer in the new GameServerSet that has a status of Allocated.

**What you expected to happen**:

The rolling update of the Fleet is expected to reduce the number of replicas of the old GameServerSet to zero after the new GameServerSet has been scaled up, regardless of the value of maxSurge or maxUnavailable.

**How to reproduce it (as minimally and precisely as possible)**:

For example, if a rolling update is performed with the following configurations and a new GameServer is allocate, the old GameServerSet will not be deleted.

```
# Fleet
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    spec:
      ports:
      - name: default
        containerPort: 7654
      template:
        spec:
          containers:
          - name: simple-game-server
            image: gcr.io/agones-images/simple-game-server:0.5
--
# FleetAutoscaler
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: simple-game-server-autoscaler
spec:
  fleetName: simple-game-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 10
      minReplicas: 10
      maxReplicas: 20
```

Allocated 5 new GameServers.
Then, the old GameServerSet is not deleted with spec.replicas set to 1.

```
$ kubectl get gs
NAME                             STATE       ADDRESS        PORT   NODE       AGE
simple-game-server-j8kvf-2v6sd   Allocated   192.168.49.2   7892   minikube   29m
simple-game-server-j8kvf-57rsn   Ready       192.168.49.2   7200   minikube   29m
simple-game-server-j8kvf-9hd2q   Ready       192.168.49.2   7434   minikube   29m
simple-game-server-j8kvf-cb5gd   Ready       192.168.49.2   7228   minikube   29m
simple-game-server-j8kvf-f4hb4   Allocated   192.168.49.2   7718   minikube   29m
simple-game-server-j8kvf-fqqnp   Ready       192.168.49.2   7189   minikube   27m
simple-game-server-j8kvf-gg46h   Ready       192.168.49.2   7748   minikube   29m
simple-game-server-j8kvf-ggcd7   Ready       192.168.49.2   7663   minikube   29m
simple-game-server-j8kvf-hpg8p   Allocated   192.168.49.2   7856   minikube   29m
simple-game-server-j8kvf-l76d2   Ready       192.168.49.2   7500   minikube   28m
simple-game-server-j8kvf-t8xsl   Ready       192.168.49.2   7124   minikube   28m
simple-game-server-j8kvf-tmzls   Ready       192.168.49.2   7708   minikube   27m
simple-game-server-j8kvf-tpmmj   Allocated   192.168.49.2   7579   minikube   29m
simple-game-server-j8kvf-w64ll   Allocated   192.168.49.2   7181   minikube   29m
simple-game-server-j8kvf-wswtg   Ready       192.168.49.2   7304   minikube   28m
simple-game-server-rsrmc-wdm64   Ready       192.168.49.2   7689   minikube   27m

$ kubectl get gameserverset
NAME                       SCHEDULING   DESIRED   CURRENT   ALLOCATED   READY   AGE
simple-game-server-j8kvf   Packed       15        15        5           10      30m
simple-game-server-rsrmc   Packed       1         1         0           1       37m
```

**Anything else we need to know?**:

**Environment**:
- Agones version: v1.19.0
- Kubernetes version (use `kubectl version`):
  - `Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:33:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}`
  - `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: minikube on MacOS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
