### ISSUE TITLE
NodeExternalDNS does not work

### ISSUE THREAD

**Issue by ctanaka-aim** [googleforgames/agones#2464]
**What happened**:
NodeExternalDNS does not work.

**What you expected to happen**:
The domain should be returned.

**How to reproduce it (as minimally and precisely as possible)**:
When installing agones with helm, I set agones.featureGates=NodeExternalDNS=true, but the result is the same as normal install.

Note that in values.yaml, there is a line   
```
featureGates=NodeExternalDNS=true
disableMTLS: true
disableTLS: true
```
in values.yaml.

The installation command is as follows
```
helm repo add agones https://agones.dev/chart/stable
helm repo update
helm install my-release --namespace agones-system -f values.yaml agones/agones
```

If you create gameservers in this state and do `kubectl get gs`, you will get the following state.
```
$ kubectl get gs
NAME                       STATE   ADDRESS        PORT   NODE                                                 AGE
simple-game-server-mfkkb   Ready   xxx.xxx.xxx.127   7091   gke-test-ctanaka-agones-default-pool-xxxxxxxxxx  3s
```

And if you do an allocate with curl, the result will look like this
````
$ curl -H "Content-Type: application/json" --data '{"namespace":"default"}' http://xxx.xxx.xxx.171/gameserverallocation -X POST
{"gameServerName":"simple-game-server-mfkkb","ports":[{"name":"default","port":7091}],"address":"xxx.xxx.xxx.127","nodeName":"gke-test-ctanaka-agones-default-pool-xxxxxxxxxx"}
````

**Environment**:
- Agones version: 1.19.0 or 1.20.0
- Kubernetes version (use `kubectl version`): v1.21.5-gke.1802
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm

**Comment by roberthbailey** [comment]
When picking the address to return, we pick in order: ExternalDNS, ExternalIP, InternalDNS, InternalIP ([source](https://github.com/googleforgames/agones/blob/main/pkg/gameservers/gameservers.go#L44-L78)). 

Since you are running on GKE this is working as intended, as GKE doesn't set an address on nodes with an external DNS name.

To confirm, I created a cluster and inspected a node:

```
...
  addresses:
  - address: 10.128.15.209
    type: InternalIP
  - address: 34.68.12.140
    type: ExternalIP
  - address: gke-issue-2464-default-pool-7e111704-rm4j.us-central1-f.c.robertbailey-agones.internal
    type: InternalDNS
  - address: gke-issue-2464-default-pool-7e111704-rm4j.us-central1-f.c.robertbailey-agones.internal
    type: Hostname
...
```

As you can see the node has an external IP (which is what is returned during allocation) but no external DNS.
