### ISSUE TITLE
gameserverselector documentation mismatch

### ISSUE THREAD

**Issue by JJhuk** [googleforgames/agones#2491]
Hi 
I found `gameserverselector` model is someting wrong

https://agones.dev/site/docs/reference/agones_crd_api_reference/#allocation.agones.dev/v1.GameServerSelector in this document's said GameServerAllocation is consist of property name like this
```
GameServerAllocation
 - LabelSelector (v1.labelSelctor) 
 - gameServerState (optional)
 - players (optional)
 ```
 
 but GameServerAllocation Specification document's says 
 https://agones.dev/site/docs/reference/gameserverallocation/
 
 ```
 selectors:
    - matchLabels:
        agones.dev/fleet: green-fleet
      players:
        minAvailable: 0
        maxAvailable: 99
    - matchLabels:
        agones.dev/fleet: blue-fleet
    - matchLabels:
        game: my-game
      matchExpressions:
        - {key: tier, operator: In, values: [cache]}
      gameServerState: Ready
      players:
        minAvailable: 0
        maxAvailable: 99
  ```
  
  I cannot find `matchLabels` and `matchExpressions` in first link, and I cannot find `LabelSelctor` in specification document.
  I checked that there are `matchExpressions` and `matchLables` inside the `LabelSelector`, but I think the first documentation is wrong so I created an issue.

I'm sorry if I misunderstood.
