### ISSUE TITLE
strange warning event when create webhook-fleet-autoscaler

### ISSUE THREAD

**Issue by JJhuk** [googleforgames/agones#2501]
**What happened**: 
`webhook-fleet-autoscaler` says 
```
Error calculating desired fleet size on FleetAutoscaler webhook-fleet-autoscaler.
Error: Post "http://autoscaler-webhook-service.multi.svc:8000/scale"
: dial tcp 172.20.36.194:8000: connect: connection refuse
```

**What you expected to happen**:
 If I command `kubectl describe webhook-fleet-autoscaler` when not any scaling Events. Event in describe maybe should be show <none>.

**How to reproduce it (as minimally and precisely as possible)**:

my `fleet.yaml` file
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: multiplay-fleet
  namespace: multi
spec:
  replicas: 2
  scheduling: Packed
  strategy:
		...
  template:
    spec:
      ports:
				....
      players:
        initialCapacity: 4
      template:
        spec:
					...
```

my `autoscaler-service.yaml` file

```
apiVersion: v1
kind: Service
metadata:
  name: autoscaler-webhook-service
  namespace: multi
  labels:
    app: autoscaler-webhook
spec:
  selector:
    app: autoscaler-webhook
  ports:
    - port: 8000
      protocol: TCP
      name: https
      targetPort: autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaler-webhook
  namespace: multi
  labels:
    app: autoscaler-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler-webhook
  template:
    metadata:
      labels:
        app: autoscaler-webhook
    spec:
      #serviceAccount: autoscaler-webhook
      containers:
        - name: autoscaler-webhook
          image: gcr.io/agones-images/autoscaler-webhook:0.4
          imagePullPolicy: Always
          ports:
            - name: autoscaler
              containerPort: 8000
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
```

my `fleetautoscaler.yaml` file

```
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: webhook-fleet-autoscaler
spec:
  fleetName: multiplay-fleet
  policy:
    type: Webhook
    webhook:
      service:
        name: autoscaler-webhook-service
        namespace: multi
        path: scale
```

1. I create fleet using `kubectl apply -f fleet.yaml -n multi`
2. because fleet's replica value is `2`, when `kubectl get gs -n multi` can get two `Ready` state gameservers
3. then command `kubectl apply -f autoscaler-service.yaml -n multi`
4. To checking pod `Running` state use `kubectl describe pod -n multi autoscaler-webhook` => Check Running
5. `kubectl apply -f fleetautoscaler.yaml -n multi`
6. `kubectl describe -n multi fleetautoscaler webhook-fleet-autoscaler`

in this tutorial https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/#4-see-the-fleet-and-autoscaler-status, 
webhook-fleet-autoscaler's event show <none>

my webhook-fleet-autoscaler's event show like this

![image](https://user-images.githubusercontent.com/31194565/156883366-0e71c0d2-0d21-4e88-a6b8-6d2bcd48bd4b.png)

```
Error calculating desired fleet size on FleetAutoscaler webhook-fleet-autoscaler.
Error: Post "http://autoscaler-webhook-service.multi.svc:8000/scale"
: dial tcp 172.20.36.194:8000: connect: connection refuse
```

**Anything else we need to know?**:

Anyway I focused two things on error event.
1. tcp
2. Error calculating desired fleet size on Fleetautoscaler webhook-fleet-autoscaler.

https://github.com/googleforgames/agones/blob/release-1.21.0/pkg/fleetautoscalers/controller.go#L296

I can found calculating error message in Agones source.
I assume relate to fleetSize.
`replicaUpperThreshold` 's defualt value is `0.7`
but my gameservers `allocatedPercent` is `0` (2 `Ready` gameserver 0 `Allocated` gameserver)

I try to change gameserver's state `Ready` to `Allocated` to achive `allocatedPercent > replicaUpperThreshold`
when my gameservers `allocatedPercent` is `1` (0 `Ready` Gameserver 2 `Allocated` gameserver), Sucessfully scalling fleet `2` to `4`
![image](https://user-images.githubusercontent.com/31194565/156883636-580ad3d2-a098-46df-b8db-fdefdea1c901.png)

**Environment**:
- Agones version: v1.21.0
- Kubernetes version (use `kubectl version`): 1.23.4
- Cloud provider or hardware configuration: aws eks
- Install method (yaml/helm): helm

I'm sorry my poor english :(
