### ISSUE TITLE
how to allocate a Local Game Server?

### ISSUE THREAD

**Issue by goace** [googleforgames/agones#2536]
the doc only shows how to register a local server to agones, but how can I allocate it ?

**Comment by roberthbailey** [comment]
Which doc are you referring to?

Whenever I need a refresher for how to allocate, I look at https://agones.dev/site/docs/getting-started/create-fleet/#4-allocate-a-game-server-from-the-fleet

For easier discovery, I wonder if moving that to a separate page under the [getting started guides](https://agones.dev/site/docs/getting-started/) would make sense.

**Comment by goace** [comment]
@roberthbailey Hi, I mean this doc https://agones.dev/site/docs/guides/local-game-server/

How can I allocate a GS which is registered as a local-game-server?

**Comment by roberthbailey** [comment]
That page says "The game server is not managed by Agones. Features like autoscaling, replication, etc are not available." I wonder if allocation is one of the features that doesn't work.

Maybe @markmandel knows offhand?

**Comment by goace** [comment]
What's the meaning of registering a local server to agones If it can't be allocated..?

**Comment by roberthbailey** [comment]
> What's the meaning of registering a local server to agones If it can't be allocated..?

You can verify the interaction between the game server and the SDK / sidecar. For example, you can verify that you are sending health pings correctly, you can watch the game server to see when metadata gets applied to it, you can set labels or annotations on the game server and see metadata propagate back to the Kubernetes resource, you can verify that you are calling `Ready()` at the correct time. If you are using the alpha features, you can set player capacity and call player connect / disconnect as well. 

It seems like it _should_ be possible to allocate a local game server though - I just haven't tried testing it myself.

**Comment by markmandel** [comment]
Sorry, I think there is confusion.

https://agones.dev/site/docs/guides/local-game-server/ refers to registering a local address for QA purposes with an existing Agones cluster. (This is different from the test local server found [here](https://agones.dev/site/docs/guides/client-sdks/local/)), which I think is what you were referring to @roberthbailey. 

If you want to allocate that `GameServer` from the cluster, then you use an Allocation with appropriate selectors that will match against it, just like you would for any other `GameServer`.

The point of it is that it looks and acts like just about any other GameServer withing the cluster, but the address points to a local instance, to make QA a bit easier to handle, so there is inherently nothing special about how you would Allocate it vs any other GameServer.

**Comment by roberthbailey** [comment]
So it sounds like it should be allocatable like any other game server and we just need to add some instructions on how to do it.

**Comment by goace** [comment]
@markmandel thanks for your reply, it make sense. 

So I can add a native k8s label to a gameserver, then I can allocate it via "matchLabels" with my custom lable, is that right?

I think you should put that in the docs to make this clear to everyone..

**Comment by goace** [comment]
I encountered a new problem, I think it's a bug.

I allocated a local game server with  my custom label successfully, bug the gameserver's state is still READY.

![image](https://user-images.githubusercontent.com/1522449/162875344-bfac09e1-b280-4a24-a452-fdb8e2b9cd49.png)

@markmandel

**Comment by goace** [comment]
for more information, this is my config files:

```yaml

# gameserver depolyment
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: local-gs
  annotations:
    agones.dev/dev-address: "192.168.1.1"
  labels:
    gstype: local
spec:
  ports:
  - name: default
    portPolicy: Static
    hostPort: 17654
    containerPort: 17654
  # The following is ignored but required due to validation.
  template:
    spec:
      containers:
      - name: simple-game-server
        image: gcr.io/agones-images/simple-game-server:0.11

# allocation
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  selectors:
    - matchLabels:
        gstype: local
  scheduling: Packed
```
