### ISSUE TITLE
The Player Capacity integration pattern example is still using the deprecated fields in the GameServerAllocation

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2570]
On https://agones.dev/site/docs/integration-patterns/player-capacity/ we have an example game server allocation using the preferred and required fields in the spec:

```
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  preferred:
    - gameServerState: Allocated
      matchLabels:
        agones.dev/fleet: lobby
      players:
        minAvailable: 10
        maxAvailable: 15
  required:
    matchLabels:
      agones.dev/fleet: lobby
```

However https://agones.dev/site/docs/reference/gameserverallocation/ says that those fields are deprecated and selectors should be used instead. We should update the Player Capacity integration pattern example to use selectors instead.
