### ISSUE TITLE
Passing configuration to the Game Server instance

### ISSUE THREAD

**Issue by Bardin08** [googleforgames/agones#2645]
**Is your feature request related to a problem? Please describe.**
I need a way to pass some configuration parameters to the allocated game server instance (can't be settled before the game server will be allocated. For example, players amount, map and etc.

**Describe the solution you'd like**
As a solution, I see an opportunity to set labels during the allocation request. If the game server allocator found a game server with the required labels it returns it, else creates a new one with specified labels.

**Describe alternatives you've considered**
- Use some king of proxy services that will keep matches configuration and then when all players will be connected fetch configuration from the proxy.
- Create several fleets with different configurations. As a disadvantage, it can be too many different configurations available.

**Comment by markmandel** [comment]
I believe this answers your question?

https://agones.dev/site/docs/faq/#how-can-i-pass-data-to-my-game-server-binary-on-allocation

**Comment by Bardin08** [comment]
Oh, sorry. It's my fault. Let me give you some more context.

1. I have an EKS cluster with deployed agones system (v.1.23.0). Agones deployed with YAML.

## Agones system

1. Agones deployed with default YAML.

<details>
<summary>Agones deployment YAML</summary>

```
kubectl create namespace agones-system
kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/release-1.23.0/install/yaml/install.yaml
```

</details>

2. Game server fleet

<details>
<summary>Game Server Fleet</summary>

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: gs-name
  namespace: agones-game-servers
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 7777
      health:
        initialDelaySeconds: 30
        periodSeconds: 60
      template:
        spec:
          containers:
          - name: gs-name
            image: $REPOSITORY/$IMAGE:$TAG
```

</details>


## Game Server allocation
Let's start from the beginning:
- I have a Game Server Binnary that has Agones SDK. It's deployed as a Game Server fleet to the EKS cluster.
- At the backend, I use C#.

1. I create a metadata object with this code snippet
<details>
<summary> Meta Data object </summary>

	  ```cs
	  var metadata = new
	  {
	      @namespace = "agones-game-servers",
	      labels = new Dictionary<string, string> {{"agones.dev/sdk-test-label", "test-label-1"}
	  };
	  ```

</details>

2. I send it as a body of the `POST` request to the `GameServerAllocation`. At the code, it looks like

<details>
<summary> Request to allocator </summary>

	  ```cs
	  var allocationResponse = await client.PostAsJsonAsync(
	      $"{_componentsConnection.GameServerAllocator.FullUri.AbsoluteUri}gameserverallocation", body);
	  ```

</details>

3. I receive an allocation result object with a valid address and port. So, a game server is allocated correctly.
<details>
<summary>Allocation result</summary>

	  ```
	  Match: {"match_id":"f49583e18edb400baeab8588a282dfaf","match_profile":"tm1","match_function":"TeamMatchStrategy","tickets":[{"id":"cat2pldnu50g9mdg7g7g","search_fields":{"tags":["tm1"],"string_args":null},"extensions":null},{"id":"cat2pldnu50g9mdg7g80","search_fields":{"tags":["tm1"],"string_args":null},"extensions":null}]}
	  {"gameServerName":"XXX-dev-fleet-mjkwn-cv4pf","ports":[{"name":"default","port":7132}],"address":"ec2-XX-XXX-XXX-111.eu-central-1.compute.amazonaws.com","nodeName":"ip-XXX-XX-XX-236.eu-central-1.compute.internal"}
	  ```

</details>

I hope now it's enough context. If you need more information, please let me know.
