### ISSUE TITLE
k8s api returned error code 403 for agones-sdk serviceaccount

### ISSUE THREAD

**Issue by shafackit** [googleforgames/agones#2671]
**What happened**:

We configured our own startup script in the `configMap` to expose the ip and port according to the value retrieved from k8s apis.

Here is our startup script in the configmap.
```
apiVersion: v1
data:
  start-script.sh: |
    #!/bin/bash
    APISERVER=https://kubernetes.default.svc
    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
    NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)
    TOKEN=$(cat ${SERVICEACCOUNT}/token)
    CACERT=${SERVICEACCOUNT}/ca.crt
    HOSTPORT=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/apis/agones.dev/v1/namespaces/${NAMESPACE}/gameservers/${HOSTNAME} 2>/dev/null|sed s/^.*hostPort\"\://g|cut -f1 -d\,)
    HOSTIP=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/apis/agones.dev/v1/namespaces/${NAMESPACE}/gameservers/${HOSTNAME} 2>/dev/null| sed 's/^.*status":{"address"//g'|cut -f2 -d\")
    echo "Fetched port:${HOSTPORT} ip:${HOSTIP} from api for host ${HOSTNAME}"
kind: ConfigMap
metadata:
  name: custom-start
  namespace: default
```

And the response that we get.
```
Fetched port:{
  "kind": "Status"
  "apiVersion": "v1"
  "metadata": {
  }
  "status": "Failure"
  "message": "gameservers.agones.dev \"our-gameserver-ngkqp-nbmtf\" is forbidden: User \"system:serviceaccount:default:agones-sdk\" cannot get resource \"gameservers\" in API group \"agones.dev\" in the namespace \"default\""
  "reason": "Forbidden"
  "details": {
    "name": "our-gameserver-ngkqp-nbmtf"
    "group": "agones.dev"
    "kind": "gameservers"
  }
  "code": 403
} ip:{
kind
apiVersion
metadata
  },
status
message
reason
details
name
group
kind
  },
code
} from api for host our-gameserver-ngkqp-nbmtf
```

**What you expected to happen**:
API to be called successfully.

**How to reproduce it (as minimally and precisely as possible)**:

We have configured certificates according to these two pages of documentation
https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/
https://agones.dev/site/docs/advanced/allocator-service/

Also attach the `fleet.yaml` for your reference. We have explicitly set the serviceAccountName to `agones-sdk`
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: our-unity-game
  namespace: default
spec:
  replicas: 3
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    # GameServer metadata
    metadata:
      namespace: default
      labels:
        game: our-unity-game
    # GameServer specification
    spec:
      ports:
      - name: default
        portPolicy: Passthrough
        protocol: TCP
        # containerPort: 7777
      health:
        disabled: true
        initialDelaySeconds: 30
        periodSeconds: 60
        failureThreshold: 10
      sdkServer:
        logLevel: Debug
        grpcPort: 9357
        httpPort: 9358
      template:
        spec:
          serviceAccountName: agones-sdk
          containers:
          - name: our-unity-game-server
            command:
            - /app/start-script.sh
            env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            image: our-unity-game-server-image
            imagePullPolicy: Always
            workingDir: /app
            volumeMounts:
            - mountPath: /app/server_Data/config-template.ini
              name: our-unity-game-config
              subPath: config.ini
            - mountPath: /app/start-script.sh
              name: custom-start
              subPath: start-script.sh
            resources:
              limits:
                cpu: 600m
                memory: 1Gi
              requests:
                cpu: 600m
                memory: 1Gi
          volumes:
          - name: our-unity-game-config
            configMap:
              name: our-unity-game-config
          - name: custom-start
            configMap:
              defaultMode: 493
              name: custom-start
          imagePullSecrets:
          - name: our-unity-game-secret

```

**Anything else we need to know?**:

**Environment**:
- Agones version: v1.24.0
- Kubernetes version (use `kubectl version`): v1.22.6
- Cloud provider or hardware configuration: Azure
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
