### ISSUE TITLE
Allow cluster autoscaler to scale down game server pods

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#2747]
**Is your feature request related to a problem? Please describe.**
[This is paraphrased from a slack conversation]

As described in https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#cluster-autoscaler-1, we currently prevent the cluster autoscaler from removing game server pods by adding the annotation `"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"`. 

For game servers that are OK being terminated (even while in the allocated state), we should make it possible for the cluster autoscaler to remove the pods to compact the cluster by removing underutilized nodes. Note that this imposes a pretty strict burden on the game server & it's configuration to have properly set graceful termination and for the game server to be able to actually gracefully terminate and finish player sessions within the configured time. As a result, we should err on the side of not enabling this by default and considering it an advanced use case. 

**Describe the solution you'd like**
A helm configuration option to change the boolean value for this particular annotation. 

Note that removing the annotation will not have the desired effect, because the cluster autoscaler does not understand that Agones-managed pods are managed and since it believes that they are un-replicated bare pods it will not remove them. Instead, we need to change the annotation to `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` to let the autoscaler know that it is safe to remove the pods. 

**Describe alternatives you've considered**
Instead of allowing the cluster autoscaler to compact the cluster and move workloads, we could write a custom controller that looks at the cluster and shuts down any game servers that can be evicted thereby compacting it from there. This would largely duplicate the functionality of the cluster autoscaler, but we could potentially add some Agones-aware logic to better choose which game servers to evict. 

**Additional context**
_n/a_

**Comment by roberthbailey** [comment]
Some notes to myself: 

* Line in question: https://github.com/googleforgames/agones/blob/9fa432c24d5aefbfcd6cf7eef61fcd4b35034663/pkg/apis/agones/v1/gameserver.go#L648 
* Cluster autoscaler FAQ for [What types of pods can prevent CA from removing a node?
](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node)

**Comment by markmandel** [comment]
Fun question for this - is there a case for being able to make this change to the Pod annotation on a per GameServer / Fleet basis, rather than all of Agones?

Given that one would need a Gracefull termination for any GameServer that is safe to evict - in a heterogeneous Fleet environment, it might be useful to specify this at the GameServer level (and thereby at the Fleet level) such that those that have a graceful termination could be safe to evict, and those that don't, are marked as not safe to evict?

WDYT?

**Comment by mtcode** [comment]
@markmandel It's a good suggestion; I'm open to this being specified on a fleet level instead of globally.  There may be cases where having the additional flexibility is beneficial such as heterogenous fleet deployments as you mentioned.

**Comment by roberthbailey** [comment]
I actually like that idea, since it moves the configuration for the autoscaler and the game server close together, making it easier for a single person to understand the relationship. You don't have to ask your cluster admin who installs and configures Agones to do it differently, you just need to specify your fleet differently, and that is the same place that you would be putting the proper graceful termination configuration as well, making it less likely that you set this new value and not the other one.

**Comment by roberthbailey** [comment]
I'm starting to look into implementing this and ran across an interesting question - how do you feel about adding the field to the game server vs. adding it to the fleet? 

Here is the game server example @markmandel gave above:

```yaml
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: "xonotic"
spec:
  autoscaler:
     safeToEvict: true # defaults to false
  ports:
    - name: default
      containerPort: 26000
  template:
    spec:
      containers:
      - name: xonotic
        image: gcr.io/agones-images/xonotic-example:0.8
```

Here is that translated to a fleet:

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: "xonotic-fleet"
spec:
  replicas: 2
  scheduling: Packed
  template:
      autoscaler:
         safeToEvict: true # defaults to false
      ports:
        - name: default
          containerPort: 26000
      template:
        spec:
          containers:
          - name: xonotic
            image: gcr.io/agones-images/xonotic-example:0.8
```

If we instead added the field to a fleet itself, then the example would look more like:

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: "xonotic-fleet"
spec:
  replicas: 2
  scheduling: Packed
  autoscaler:
    safeToEvict: true # defaults to false
  template:
      ports:
        - name: default
          containerPort: 26000
      template:
        spec:
          containers:
          - name: xonotic
            image: gcr.io/agones-images/xonotic-example:0.8
```

It feels to me like autoscaler related settings fit better into a fleet spec, similarly to how a fleet has a `scheduling` field which relates to spreading vs packing game servers. This is reinforced by looking at the code block I linked to earlier, where we only apply the annotation if the scheduling is set to packed:

```go
if gs.Spec.Scheduling == apis.Packed {
	// This means that the autoscaler cannot remove the Node that this Pod is on.
	// (and evict the Pod in the process)
	pod.ObjectMeta.Annotations["cluster-autoscaler.kubernetes.io/safe-to-evict"] = "false"
}
```

WDYT about adding the field to the game server spec vs. the fleet spec? Are there any cases where we would want to be able to set this on a game server outside of the context of a fleet?

**Comment by markmandel** [comment]
I would argue that it makes the most sense to have it on the GameServer, since that is the most flexible implementation (maybe someone doesn't actually use a Fleet at all?).

But to note, when referencing `Scheduling` a `GameServer` does actually have a `scheduling` field in [GameServerSpec](https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServerSpec) - it just mainly gets populated by the Fleet, because in the code you referenced, we need to know at the GameServer level what the scheduling value is. So either way, you will need to add it to a GameServer I expect.

https://github.com/googleforgames/agones/blob/dc3eb37f05e5c567e3d642ef4a77f0e59e993446/pkg/apis/agones/v1/gameserverset.go#L125-L131

That being said, I'm surprised we only set it on Packed 🤔 (although I wrote it, so go figure) - I guess the theory being that on-prem you likely wouldn't have a autoscaler, since it's static machine configurations.

**Comment by roberthbailey** [comment]
> But to note, when referencing Scheduling a GameServer does actually have a scheduling field in [GameServerSpec](https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServerSpec) - it just mainly gets populated by the Fleet, because in the code you referenced, we need to know at the GameServer level what the scheduling value is.

Huh, this isn't documented in https://agones.dev/site/docs/reference/gameserver/ (where I was looking) but when I look into the source there it is: https://github.com/googleforgames/agones/blob/main/pkg/apis/agones/v1/gameserver.go#L152

**Comment by roberthbailey** [comment]
One other way to go about this would be to only write the `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation if it isn't explicitly set in the game server's pod metadata. 

Right now, our code will overwrite it even if it is set explicitly, e.g.

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 2
  template:
    spec:
      ports:
      - name: default
        containerPort: 7654
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        spec:
          containers:
          - name: simple-game-server
            image: gcr.io/agones-images/simple-game-server:0.13
```

produces the same result as 

```yaml
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server-2
spec:
  replicas: 2
  template:
    spec:
      ports:
      - name: default
        containerPort: 7654
      template:
        spec:
          containers:
          - name: simple-game-server
            image: gcr.io/agones-images/simple-game-server:0.13
```

If we only set the annotation if it wasn't already explicitly set, then the first yaml example here would work as expected without us needing to introduce any new fields into the Agones API.
