### ISSUE TITLE
GameServerAllocation example yaml file has incorrect format for selectors

### ISSUE THREAD

**Issue by john-haven** [googleforgames/agones#2853]
**What happened**:

The GameServerAllocation example yaml file has the incorrect format for it's selectors:
https://github.com/googleforgames/agones/blob/release-1.27.0/examples/gameserverallocation.yaml#L38-L45
You're missing the `labelSelector`, I believe this is because it is *missing* a `json:",inline"` for it's json tag:
https://github.com/googleforgames/agones/blob/release-1.27.0/pkg/apis/allocation/v1/gameserverallocation.go#L103

Also the usage of the `matchExpressions` selector could be clearer for yaml, I've updated that below too.

**What you expected to happen**:
The examples should deserialize correctly from yaml to into a `v1.GameSeverAllocation object.

The following format deserializes correctly for me into a `v1.GameSeverAllocation` and I think is clearer for the example:
```
spec:
  selectors:
  - labelSelector:
      matchLabels:
        agones.dev/fleet: green-fleet
  - labelSelector:
      matchLabels:
        agones.dev/fleet: blue-fleet
  - labelSelector:
      matchLabels:
        game: my-game
  - labelSelector:
      matchExpressions:
      - key: tier
        operator: In
        values:
        - cache
  - labelSelector:
    gameServerState: Ready
  - labelSelector:
    players:
      minAvailable: 0
      maxAvailable: 99
```
Alternatively I think you could likely fix the `json:",inline"` missing from the `LabelSelector` to resolve the issue to match the examples, but I didn't test that.

**How to reproduce it (as minimally and precisely as possible)**:

Here's a short program I wrote to dump the spec
```
package main

import (
	"fmt"

	agonesv1 "agones.dev/agones/pkg/apis/agones/v1"
	allocv1 "agones.dev/agones/pkg/apis/allocation/v1"
	"github.com/davecgh/go-spew/spew"
	"gopkg.in/yaml.v2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func main() {
	readyState := agonesv1.GameServerStateReady

	gsAllocation := allocv1.GameServerAllocation{
		Spec: allocv1.GameServerAllocationSpec{
			Selectors: []allocv1.GameServerSelector{
				{
					LabelSelector: metav1.LabelSelector{
						MatchLabels: map[string]string{
							"agones.dev/fleet": "green-fleet",
						},
					},
				},
				{
					LabelSelector: metav1.LabelSelector{
						MatchLabels: map[string]string{
							"agones.dev/fleet": "blue-fleet",
						},
					},
				},
				{
					LabelSelector: metav1.LabelSelector{
						MatchLabels: map[string]string{
							"game": "my-game",
						},
					},
				},
				{
					LabelSelector: metav1.LabelSelector{
						MatchExpressions: []metav1.LabelSelectorRequirement{
							{
								Key:      "tier",
								Operator: "In",
								Values:   []string{"cache"},
							},
						},
					},
				},
				{
					GameServerState: &readyState,
				},
				{
					Players: &allocv1.PlayerSelector{
						MinAvailable: 0,
						MaxAvailable: 99,
					},
				},
			},
		},
	}
	spew.Dump(gsAllocation)

	out, err := yaml.Marshal(gsAllocation)
	if err != nil {
		fmt.Printf("error: %v", err)
		return
	}
	fmt.Println(string(out))
}
```

**Anything else we need to know?**:

Due to my internal policies I am unable to open a PR for this. My apologies.

**Environment**:
- Agones version: 1.27.0
- Kubernetes version (use `kubectl version`): n/a
- Cloud provider or hardware configuration: n/a
- Install method (yaml/helm): n/a
- Troubleshooting guide log(s): n/a
- Others: n/a
