### ISSUE TITLE
The pods pulled by the game service are automatically marked with the affinity of pods

### ISSUE THREAD

**Issue by liangpeihuahua** [googleforgames/agones#2856]
**What happened**:

The pods pulled by the game service are automatically marked with the affinity of pods, resulting in uneven distribution of pods in the cluster
**What you expected to happen**:
Don't let the pod automatically mark affinity

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.26
- Kubernetes version (use `kubectl version`):1.22
- Cloud provider or hardware configuration:aws
- Install method (yaml/helm):helm
- Troubleshooting guide log(s):
-
![image](https://user-images.githubusercontent.com/118984957/206189448-a46ec75e-d240-4b4a-92e2-525412cb179c.png)

- Others:

**Comment by liangpeihuahua** [comment]
but i don't have set podaffinity for fleet or gameservice

**Comment by markmandel** [comment]
Assuming you mean `Pods` for `GameServers` (please correct me if I'm wrong), this is by design:

If you would like to have a more distributed scheduling (say if you are on-prem, rather than in the Cloud_, then that is why we have the `Distributed` scheduling strategy.

See:
* https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#pod-scheduling-strategy
* https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#pod-scheduling-strategy-1

But let me know if that doesn't solve your issue 👍🏻

**Comment by liangpeihuahua** [comment]
I have a requirement. When we need to publish a fleet to the specified 3 servers(node), this should have a field setting, because kubernetes can set NodeSelector

**Comment by liangpeihuahua** [comment]
> Assuming you mean `Pods` for `GameServers` (please correct me if I'm wrong), this is by design:
> 
> If you would like to have a more distributed scheduling (say if you are on-prem, rather than in the Cloud_, then that is why we have the `Distributed` scheduling strategy.
> 
> See:
> 
> * https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#pod-scheduling-strategy
> * https://agones.dev/site/docs/advanced/scheduling-and-autoscaling/#pod-scheduling-strategy-1
> 
> But let me know if that doesn't solve your issue 👍🏻

I have a requirement. When we need to publish a fleet to the specified 3 servers(node), this should have a field setting, because kubernetes can set NodeSelecto

**Comment by liangpeihuahua** [comment]
The test results are as follows. The scheduling strategy of the fleet is adjusted to scheduling: Distributed. As a result, all pods  control by this fleet are still scheduled to the same node. Not balanced to each node.

**Comment by markmandel** [comment]
> The test results are as follows. The scheduling strategy of the fleet is adjusted to scheduling: Distributed. As a result, all pods control by this fleet are still scheduled to the same node. Not balanced to each node.

Distributed utilises whatever the default scheduler is on the cluster, and sets no affinity. Depending on your Kubernetes cluster setup, if you have alternative schedulers in place, they can affect how things are scheduled.

If you wish, set your own anti-affinity to have more control over Pod scheduling.

**Comment by liangpeihuahua** [comment]
Can fleet support me to set anti-affinity, and how can I set my own anti-affinity in the fleet

**Comment by liangpeihuahua** [comment]
I set the scheduling strategy to Distributed. I have tried many times, but the result is the same. At the same time, I did another comparative experiment, creating a deployment without setting any affinity, and the copies of the pod can be evenly distributed to each node.
![image](https://user-images.githubusercontent.com/118984957/206645969-1399c987-3756-4be9-a533-b1386e62471b.png)

**Comment by markmandel** [comment]
What does your Fleet configuration look like, and what does the resultant Pod yaml look like for a GameServer?

If you want to set your own affinities, the GameServer contains a full `PodTemplateSpec`

https://agones.dev/site/docs/reference/agones_crd_api_reference/#agones.dev/v1.GameServerSpec

**Comment by liangpeihuahua** [comment]
fleet yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  annotations:
    agones.dev/sdk-version: 1.27.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {xxxxxxxxxxx}
  creationTimestamp: "2022-11-14T11:28:33Z"
  generation: 9
  name: xxxxxxxx
  namespace: default
spec:
  replicas: 10
  scheduling: Distributed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      health: {}
      ports:
      - name: roomserver
        portPolicy: Passthrough
        protocol: TCP
      - name: frameserver
        portPolicy: Passthrough
        protocol: TCP
      - name: watchdog
        portPolicy: Passthrough
        protocol: TCP
      sdkServer: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            imagePullPolicy: Always
            name: xxxxxxxxx
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 200Mi
status:
  allocatedReplicas: 0
  readyReplicas: 10
  replicas: 10
  reservedReplicas: 0



pod yaml

apiVersion: v1
kind: Pod
metadata:
  annotations:
    agones.dev/container: xxxxxxxxxxxxxxxxxxxxxx
    agones.dev/ready-container-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    agones.dev/sdk-version: 1.27.0
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-12-08T09:15:46Z"
  labels:
    agones.dev/gameserver: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    agones.dev/role: gameserver
  name: xxxxxxxxxxxxxxxx
  namespace: default
  ownerReferences:
  - apiVersion: agones.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: GameServer
    name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spec:
  containers:
  - args:
    - --grpc-port=9357
    - --http-port=9358
    env:
    - name: GAMESERVER_NAME
      value: xxxxxxxxxxxxxxxxx
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: FEATURE_GATES
      value: CustomFasSyncInterval=true&Example=true&PlayerAllocationFilter=false&PlayerTracking=false&ResetMetricsOnDelete=false&SDKGracefulTermination=false&StateAllocationFilter=true
    image: gcr.io/agones-images/agones-sdk:1.27.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: agones-gameserver-sidecar
    resources:
      requests:
        cpu: 30m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-56csf
      readOnly: true
  - env:
    - name: AGONES_SDK_GRPC_PORT
      value: "9357"
    - name: AGONES_SDK_HTTP_PORT
      value: "9358"
    image: xxxxxxxxxxxxxxxxxxxxx
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /gshealthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: xxxxxxxxxxxx
    ports:
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: empty
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: xxxxxxxxxxxxxxxxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: agones-sdk
  serviceAccountName: agones-sdk
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: empty
  - name: kube-api-access-56csf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

**Comment by markmandel** [comment]
Sorry - that's not very legible, would you mind editing the above response it so the contents are inside a \``` code block please?

But giving it a glance, there is no affinity set on the Pod, so there must be something in the AWS EKS scheduler that is causing the pods to be grouped together.

`Distributed` uses whatever the default scheduler is in the cluster (which by default should be distributed across nodes) - so it may be time to talk to EKS and see what settings you are providing the cluster to see what is causing the compaction.

As an aside - if you are on EKS, why do you want it distributed? Wouldn't you want it compacted so you can pay the least amount for your cloud usage? I had actually assumed you were on physical hardware/on-prem, but I just checked your original post's details.

**Comment by liangpeihuahua** [comment]
fleets
```
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  annotations:
    agones.dev/sdk-version: 1.27.0
    kubectl.kubernetes.io/last-applied-configuration: |
      {xxxxxxxxxxx}
  creationTimestamp: "2022-11-14T11:28:33Z"
  generation: 9
  name: xxxxxxxx
  namespace: default
spec:
  replicas: 10
  scheduling: Distributed
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
    spec:
      health: {}
      ports:
      - name: roomserver
        portPolicy: Passthrough
        protocol: TCP
      - name: frameserver
        portPolicy: Passthrough
        protocol: TCP
      - name: watchdog
        portPolicy: Passthrough
        protocol: TCP
      sdkServer: {}
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
            imagePullPolicy: Always
            name: xxxxxxxxx
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
              requests:
                cpu: 100m
                memory: 200Mi
status:
  allocatedReplicas: 0
  readyReplicas: 10
  replicas: 10
  reservedReplicas: 0

```

gs-pod
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    agones.dev/container: xxxxxxxxxxxxxxxxxxxxxx
    agones.dev/ready-container-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    agones.dev/sdk-version: 1.27.0
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-12-08T09:15:46Z"
  labels:
    agones.dev/gameserver: xxxxxxxxxxxxxxxxxxxxxxxxxxx
    agones.dev/role: gameserver
  name: xxxxxxxxxxxxxxxx
  namespace: default
  ownerReferences:
  - apiVersion: agones.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: GameServer
    name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
spec:
  containers:
  - args:
    - --grpc-port=9357
    - --http-port=9358
    env:
    - name: GAMESERVER_NAME
      value: xxxxxxxxxxxxxxxxx
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: FEATURE_GATES
      value: CustomFasSyncInterval=true&Example=true&PlayerAllocationFilter=false&PlayerTracking=false&ResetMetricsOnDelete=false&SDKGracefulTermination=false&StateAllocationFilter=true
    image: gcr.io/agones-images/agones-sdk:1.27.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 3
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    name: agones-gameserver-sidecar
    resources:
      requests:
        cpu: 30m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-56csf
      readOnly: true
  - env:
    - name: AGONES_SDK_GRPC_PORT
      value: "9357"
    - name: AGONES_SDK_HTTP_PORT
      value: "9358"
    image: xxxxxxxxxxxxxxxxxxxxx
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /gshealthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    name: xxxxxxxxxxxx
    ports:
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    - containerPort: xxxx
      hostPort: xxxx
      protocol: TCP
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: empty
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: xxxxxxxxxxxxxxxxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: agones-sdk
  serviceAccountName: agones-sdk
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: empty
  - name: kube-api-access-56csf
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
```

I also have physical hardware/on-prem environment。

As an aside -
