### ISSUE TITLE
Local SDK server returns 500 on player-connect

### ISSUE THREAD

**Issue by luckyswede** [googleforgames/agones#2880]
Hey,
We're trying out the player-tracking feature using the local sdk server, however enabling the feature-flag and setting spec -> players -> initalCapacity in the gamserver yaml makes agones return http 500 on player-connect requests.

gameserver.yaml:
```
apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: dev-server
spec:
  ports:
  - name: default
    portPolicy: Dynamic
    containerPort: 7777
  players:
    initialCapacity: 10
  template:
    spec:
      containers:
      - name: simple-game-server
        image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.14
```

Starting Agones:
`./sdk-server.darwin.arm64 --local --feature-gates PlayerTracking=true -f gameserver.yaml`

Player-connect:
```
$> curl -d '{"playerID": "user-123"}' -H "Content-Type: application/json" http://localhost:9358/alpha/player/connect -v
< HTTP/1.1 500 Internal Server Error
{"error":"Players are already at capacity","code":2,"message":"Players are already at capacity"}
```

To make it work I have to set the player-capacity using the API:
`$> curl -d '{"count": 10}' -H "Content-Type: application/json" -X PUT http://localhost:9358/alpha/player/capacity`
...and now the player-connect call works.
The installed Agones we run in GKE does not have this behavior, it accepts player-connect calls without requiring the server to explicitly set the capacity using the API.

Maybe this is related to #2709 

Agones version: agonessdk-server-1.27.0
