### ISSUE TITLE
How to connect gameserver that has no container port on it.

### ISSUE THREAD

**Issue by portlek** [googleforgames/agones#3024]
So basically, i'm creating a Minecraft server which has Proxies and also gameplay servers. I don't want to expose gameplay servers to players but proxies do. Proxies are registering gameplay servers internally to move the player whenever it connects to the proxy. My gameserver fleet yaml looks like this:
```yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: hub-fleet
  namespace: minecraft
spec:
  replicas: 2
  scheduling: Packed
  template:
    spec:
      ports:
        - name: minecraft-port
          containerPort: 25565 // I want to make this port only accessible within the kubernetes network like ClusterIp type service.
          protocol: TCP
      template:
        spec:
          serviceAccountName: minecraft-account
          containers:
            - name: hub-gameserver
              image: MY_IMAGE
```
I know 'ports' is nullable since 1.30.0 (i guess?) but when i remove the ports, how i supposed to send people to this gameplay server? Or if there is a way to make the port something like 'ClusterIp' rather than like a NodeIp would be great too.

I've tried to create a new container port within the gameserver pod, i guess kubernetes does not allow that.

**Comment by aimuz** [comment]
The ports part fill in the ports you want to expose. If your game service wants to be exposed through the proxy service, you should fill in the ports of the proxy in ports. You can run multiple containers in one pod.

Take for example

```
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: hub-fleet
  namespace: minecraft
spec:
  replicas: 2
  scheduling: Packed
  template:
    spec:
      ports:
        - name: proxy-port
          containerPort: 1234
          protocol: TCP
      template:
        spec:
          serviceAccountName: minecraft-account
          containers:
            - name: proxy # port: 1234
              image: MY_IMAGE
            - name: hub-gameserver #  port: 25565
              image: MY_IMAGE
```
