### ISSUE TITLE
Using Agones with GKE Config Sync

### ISSUE THREAD

**Issue by nway-gcp** [googleforgames/agones#3140]
Can I get any help about this? I tried other helm chart like mysql, it's working correctly.
I cannot find any clue of this issue. If I get any helps, I really appreciate it.

**What happened**:
KNV2001: Object 'Kind' is missing in 'null' path: /repo/source/agones:1.31.0/agones/templates/extensions-deployment.yaml For more information, see https://g.co/cloud/acm-errors#knv2001

Got this error using GKE Config Sync

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the RootSync with this script:

```
apiVersion: configsync.gke.io/v1alpha1
kind: RootSync
metadata:
  name: agones
  namespace: config-management-system
spec:
  sourceType: helm
  sourceFormat: unstructured
  helm:
    repo: https://agones.dev/chart/stable
    chart: agones
    version: 1.31.0
    releaseName: agones
    namespace: agones-system
    auth: none
    values:
      gameservers:
        namespaces: [default, dev, stage, demo]
      agones:
        allocator:
          disableMTLS: true
          diableTLS: true
          service:
            http:
              port: 30000
            grpc:
              port: 30000
            loadBalancerSourceRanges: [10.117.128.0/17]
```

**Anything else we need to know?**:

**Environment**:
- Agones version:  1.31.0
- Kubernetes version (use `kubectl version`): 1.25.7-gke.1000 standard
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): Helm and Anthos Configuration Management System
- Troubleshooting guide log(s):
- Others:
