### ISSUE TITLE
Why the gameserver fleet is getting shutdown by itself

### ISSUE THREAD

**Issue by SomendraDev** [googleforgames/agones#3204]
### Fleet file : 
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: andarbahar-fleet
  namespace: pfcpro
  labels:
    app: andarbahar-fleet
spec:
  replicas: 1
  scheduling: Packed
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: andarbahar-gameserver
        agonesdevfleet: andarbahar-fleet
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 443
          protocol: TCP
      health:
        initialDelaySeconds: 60
        periodSeconds: 60
      sdkServer:
        logLevel: Info
        grpcPort: 9357
        httpPort: 9358
      template:
        spec:
          containers:
            - name: andarbahar-gameserver
              image: sonu121/andarbahargameserver:2
              imagePullPolicy: Always
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
                limits:
                  cpu: 300m
                  memory: 300Mi
              envFrom:
                - configMapRef:
                    name: pfcpro-games-config-map
              env:
                - name: AZURE_TABLE_GRAIN_STORAGE_TABLE_NAME
                  value: "andarbaharGamesTable3" # in minutes
                - name: AZURE_TABLE_GRAIN_REMINDER_TABLE_NAME
                  value: "andarbaharReminderTable3" # in minutes
                - name: DELAY_DEACTIVATION_OF_GRAIN
                  value: "60" # in minutes
                - name: AMOUNT_TO_BE_COLLECTED
                  value: "10"
          restartPolicy: Always

```
### FleetAutoscaler file :
```

apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler-andarbahar
  namespace: pfcpro
spec:
  fleetName: store-andarbahar-fleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      maxReplicas: 1
  sync:
    type: FixedInterval
    fixedInterval:
      seconds: 30
```

### Messaged got when auto shutdown : 

![image](https://github.com/googleforgames/agones/assets/106752882/a1450205-cc93-4919-b861-8b55a561958a)
