### ISSUE TITLE
agones-ping merge to use a single port

### ISSUE THREAD

**Issue by aimuz** [googleforgames/agones#3236]
I have noticed so far that agones-ping service provides two services to the public, but observed that they are both provided by one port.

Based on this can we combine agones-ping-http-service and agones-ping-udp-service into one service

.e.g.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: agones
    meta.helm.sh/release-namespace: agones-system
  labels:
    app: agones
    app.kubernetes.io/managed-by: Helm
    chart: agones-1.32.0
    component: ping
    heritage: Helm
    release: agones
  name: agones-ping
  namespace: agones-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: udp
    port: 80
    protocol: UDP
    targetPort: 8080
  selector:
    agones.dev/role: ping
  sessionAffinity: None
  type: LoadBalancer
```
