### ISSUE TITLE
 If a fleet has replicas specified, the fleet allocator will fail to scale the fleet to more than N replicas specified in the fleet spec.

### ISSUE THREAD

**Issue by dmitryrn** [googleforgames/agones#3356]
**What happened**:
If a fleet has replicas specified,  the fleet allocator will fail to scale the fleet to more than N replicas specified in the fleet spec.

**What you expected to happen**:
fleet autoscaler ignores fleet's `replicas` value and scales up using autoscaler's configuration.
 
**How to reproduce it (as minimally and precisely as possible)**:
```
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: fleet1
  namespace: dev-server
  labels:
    fleetset: "1"
spec:
  replicas: 2
  scheduling: Distributed
  strategy:
    type: Recreate
  template:
    spec:
      ports:
      - name: default
        containerPort: 7777
        portPolicy: Dynamic
        protocol: UDP
      health:
        disabled: true
      sdkServer:
        logLevel: Debug
      template:
        metadata:
          labels:
            gameserver: gameserver
        spec:
          containers:
          - name: gameserver
            imagePullPolicy: Always
            image: yourimage
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: fleet1-autoscaler
  namespace: dev-server  
spec:
  fleetName: fleet1
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 2
      maxReplicas: 200
```
game server source code:
```
package main

import (
	"time"

	sdk "agones.dev/agones/sdks/go"
)

func main() {
	sdk, err := sdk.NewSDK()
	if err != nil {
		panic(err)
	}

	err = sdk.Ready()
	if err != nil {
		panic(err)
	}

    time.Sleep(time.Hour*999)
}
```

Allocate a game server with an allocation:
```
apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: fleet1
    - matchLabels:
        fleetset: "1"
      gameServerState: Ready
  scheduling: Packed

```
allocate 2 times, and notice that the third game server is shutting down right after it starts over and over.

**Anything else we need to know?**:
The solution is to remove replicas from the fleet spec, but it took some time to figure out why it wasn't working as expected.

**Environment**:
- Agones version: 1.33.0
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"archive", BuildDate:"2023-07-20T07:37:53Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
