### ISSUE TITLE
Agones Controller Memory leak to 460M

### ISSUE THREAD

**Issue by alvin-7** [googleforgames/agones#3380]
**What happened**:
Agones controller memory usage leak to 460M

**What you expected to happen**:
Agones controller memory usage stays at normal level, not spike unreasonably

**How to reproduce it (as minimally and precisely as possible)**:
Unable to provide specific steps to reproduce currently. This spike happened during normal usage.

**Anything else we need to know?**:
Unable to get agones_gameservers_count from metrics at 460M memory usage
Memory usage recovers to normal 40M+ after Agones controller has OOMKilled

**Environment**:
- Agones version:  1.34.0
- Kubernetes version (use `kubectl version`): 1.22
- Cloud provider or hardware configuration: Tencent Cloud
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): 
- Others:
![image](https://github.com/googleforgames/agones/assets/38536867/91563346-f285-457b-9dba-0607d367d012)
![image](https://github.com/googleforgames/agones/assets/38536867/920269bb-cfca-4a3c-ab0f-fee02d0c2cfe)

**Comment by ashutosji** [comment]
Hi @alvin-7,
It's hard to identify the cause of this issue. Can we get logs and events? Also, If you can provide the resource requests and limits.

**Comment by markmandel** [comment]
@gongmax have you seen anything like this in your performance tests?

Also just wondering if Agones contoller uses a bunch of memory because of all caching, and so this is actually "works as intended" ?

We have a way to build the controller with pprof enabled (not enabled in production builds), I wonder if there's a way to make it a command line argument instead.

https://github.com/googleforgames/agones/tree/main/build#i-want-to-use-pprof-to-profile-the-controller

**Comment by gongmax** [comment]
I didn't see exact same thing but from my experience the memory used do related to the fleet size, i.e. larger fleet come with more controller memory used.

**Comment by markmandel** [comment]
I'll also ask:

>  This spike happened during normal usage.

What is "normal usage"?

* one fleet? 3?
* Rolling updates? or none?
* Allocations?
* SDK Usage?

**Comment by alvin-7** [comment]
> I'll also ask:
> 
> > This spike happened during normal usage.
> 
> What is "normal usage"?
> 
> * one fleet? 3?
> * Rolling updates? or none?
> * Allocations?
> * SDK Usage?

* 11 or more fleets; 30 or more Gameservers
* Rolling update
* What do you mean by "Allocation"? Gameserver have been allocated and destroyed after use.
* SDK in use

Now memory usage is 102MB，there is grafana pannel:
![image](https://github.com/googleforgames/agones/assets/38536867/c4207d24-73ed-480f-9098-c30360f34d46)

My fleet configuration:
```
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: fleet-example
  namespace: default
spec:
  replicas: 3
  scheduling: Packed
  strategy:
    type: Recreate
  template:
    spec:
      container: gameserver
      health:
        failureThreshold: 3
        initialDelaySeconds: 45
        periodSeconds: 10
      ports:
        - container: gameserver
          containerPort: 7777
          name: ue
          portPolicy: Dynamic
          protocol: UDP
        - container: gameserver
          containerPort: 7778
          name: grpc
          portPolicy: Dynamic
          protocol: TCP
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: 'false'
        spec:
          containers:
            - image: 'image_url'
              imagePullPolicy: Always
              name: gameserver
              resources:
                limits:
                  cpu: 800m
                  memory: 2Gi
                requests:
                  cpu: 800m
                  memory: 256Mi
```
