### ISSUE TITLE
Counters: Default capacity should be 0 (max), not 1000

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3579]
**What happened**:

Creating a Fleet with the following yaml:

```yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 7654
      counters:
        rooms:
          count: 0
      lists:
        players:
          values: []
      template:
        spec:
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.23
              resources:
                requests:
                  memory: 64Mi
                  cpu: 20m
                limits:
                  memory: 64Mi
                  cpu: 20m
```

When I look at the resulting yaml output, I see that the default capacity is 1000 in the counter status:

```yaml
status:
  address: XX.XXX.XXX.XXX
  addresses:
  - address: XX.XXX.XXX.XXX
    type: InternalIP
  - address: XX.XXX.XXX.XXX
    type: ExternalIP
  - address: gke-test-cluster-default-393bd66b-swtm
    type: Hostname
  counters:
    rooms:
      capacity: 1000 # ⬅️ is the issue
      count: 0
  eviction:
    safe: Never
  immutableReplicas: 1
  lists:
    players:
      capacity: 1000
      values: []
  nodeName: gke-test-cluster-default-393bd66b-swtm
  ports:
  - name: default
    port: 7889
  reservedUntil: null
  state: Ready
```

**What you expected to happen**:

[Link to relevant design](https://github.com/googleforgames/agones/issues/2716#:~:text=Counters%20can%20have%20a%20set%20capacity%20(maximum%20value)%2C%20but%20by%20default%20are%200%20(max%20of%20int64))

`capacity` should be 0, since it's a counter, and we don't need to limit its size for performance reasons.

**How to reproduce it (as minimally and precisely as possible)**:

Apply yaml above, then `kubectl get gs <name> -o yaml` to see the result.

**Anything else we need to know?**:

N/A

**Environment**:
- Agones version:   1.37.0
- Kubernetes version (use `kubectl version`): v1.27.7-gke.1056000
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others: N/A
