### ISSUE TITLE
No validation on GameServerAllocation.Priorities

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#3684]
**What happened**:

You can pass in invalid values for priority.type and priority.order on a `GameServerAllocation`

**What you expected to happen**:

Return an error stating the values are invalid (this happens with a Fleet - but it has the OpenAPI Spec).

**How to reproduce it (as minimally and precisely as possible)**:

Create this Fleet:

```yaml
apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 2
  template:
    spec:
      ports:
        - name: default
          containerPort: 7654
      counters:
        rooms:
          count: 0
          capacity: 10
      lists:
        players:
          values: []
      template:
        spec:
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.27
              resources:
                requests:
                  memory: 64Mi
                  cpu: 20m
                limits:
                  memory: 64Mi
                  cpu: 20m
```
Then `kubectl create -f <this file>`:

```yaml
apiVersion: allocation.agones.dev/v1
kind: GameServerAllocation
spec:
  scheduling: Packed
  priorities:
    - type: John
      key: rooms
      order: Dog
  selectors:
    # First check to see if we can back-fill an already allocated `GameServer`
    - gameServerState: Allocated
      matchLabels:
        agones.dev/fleet: simple-game-server
      counters:
        rooms:
          minAvailable: 1
   # If we can't, then go get a `Ready` `GameServer`.
    - gameServerState: Ready
      matchLabels:
        agones.dev/fleet: simple-game-server
      counters:
        rooms:
          minAvailable: 1
  counters:
    rooms:
      action: Increment
      amount: 1
```

It will complete with no error.

**Anything else we need to know?**:

Since GameServerAllocation doesn't have the OpenAPI spec, we will have to do this somewhere in the `.Validate()` function of GameServerAllocation.

https://github.com/googleforgames/agones/blob/1c536c0aec680e8b013479bc15481c4ae47e3185/pkg/apis/allocation/v1/gameserverallocation.go#L376

**Environment**:
- Agones version: dev
- Kubernetes version (use `kubectl version`): 1.28
- Cloud provider or hardware configuration: GKE
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): N/A
- Others: N/A
