### ISSUE TITLE
Autoscaler WebHook fallback Policy

### ISSUE THREAD

**Issue by nrwiersma** [googleforgames/agones#3686]
**Is your feature request related to a problem? Please describe.**
While using the Autoscaler WebHook, it is possible, if not guaranteed, that at some point the service the WebHook points to will become unavailable for some or other reason. If the service does not recover within the autoscaling interval the fleets will not scale at all.

**Describe the solution you'd like**
It would be useful to be able to configure both the WebHook and another Policy (e.g. BufferPolicy). If the WebHook fails to respond, the other policy would be used. If no other policy is specified, the current behaviour persists, in that no replica change is made. Perhaps there could be a WebHook failure allowance (number of allowed failures) before the other Policy is used.

**Describe alternatives you've considered**
There are none. As it stands it is all or nothing with the WebHook.

**Additional context**
While it is obviously not desirable for the WebHook service to be unavailable for extended periods, anyone that has seen production knows that this unfortunately happens. This feature would bring a measure of resilience when using a WebHook.

**Comment by markmandel** [comment]
This sounds like a good thing 👍🏻 

Any suggestions on what the configuration should look like?

**Comment by nrwiersma** [comment]
I would keep the config the same, but the addition of something like `Fallback: true` on the WebHook config. As it stands, the autoscaler validation does not stop you from setting multiple policies, they just get validated in a specific order. My moving WebHook forward in that list and checking `Fallback` it could continue down the list to find the next policy to validate, and the implementation would basically work the same.

Should allowing a number of failures before fallback be desired, that too could be added to the WebHook.

**Comment by nrwiersma** [comment]
Actually, that would not work, you would need a `FallbackType` to specify which type you want to fallback to.

**Comment by markmandel** [comment]
I was thinking some kind of nested config under `webhook`?

```yaml
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: webhook-fleet-autoscaler
spec:
  fleetName: simple-game-server
  policy:
    # type of the policy - this example is Webhook
    type: Webhook
    # parameters for the webhook policy - this is a WebhookClientConfig, as per other K8s webhooks
    webhook:
      # use a service, or URL
      service:
        name: autoscaler-webhook-service
        namespace: default
        path: scale
      fallback: # Basically this is a copy of the above - so you could fallback to another webhook - but only allow one level
        policy:
          type: Buffer
          buffer:
            bufferSize: 5
            minReplicas: 10
            maxReplicas: 20
```
