### ISSUE TITLE
[mTLS]:  allocator server can not verify client certificate when client certificate auto renew

### ISSUE THREAD

**Issue by GStones** [googleforgames/agones#3812]
**What happened**:
`Allocator server` can not verify the client certificate when the client certificate auto-renew
**What you expected to happen**:
 Can verify the client certificate when the client certificate auto-renew
**How to reproduce it (as minimally and precisely as possible)**:
Renew the client certificate files

**Environment**:
- Agones version:  v1.40.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install method (yaml/helm):
``` yaml
  - name: tls-client
    csi:
      readOnly: true
      driver: csi.cert-manager.io
      volumeAttributes:
        csi.cert-manager.io/issuer-name: "ca-name"
        csi.cert-manager.io/issuer-kind: "AWSPCAClusterIssuer"
        csi.cert-manager.io/issuer-group: "awspca.cert-manager.io"
        csi.cert-manager.io/common-name: "${SERVICE_ACCOUNT_NAME}.${POD_NAMESPACE}"
        csi.cert-manager.io/duration: "1h"
        csi.cert-manager.io/renew-before: "10m"
```
``` yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: allocator-tls
  namespace: agones-system
spec:
  commonName: agones-allocator
  dnsNames:
    - "agones-allocator.agones-system.svc.cluster.local"
  duration: 1h0m0s
  issuerRef:
    group: awspca.cert-manager.io
    kind: AWSPCAClusterIssuer
    name: ca-name
  renewBefore: 0h10m0s
  secretName: allocator-tls
```
- Troubleshooting guide log(s):
 
``` json
    {"error":"x509: certificate has expired or is not yet valid: current time 2024-05-08T09:35:08Z is after 2024-05-08T07:39:46Z","mes  │ sage":"failed to verify client certificate","severity":"warning","source":"main","time":"2024-05-08T09:35:08.759941866Z"}

 ```
- Others:
