### ISSUE TITLE
Beta: UpdateList using Agones 1.41 rest API doesn't update the data in the selected list

### ISSUE THREAD

**Issue by Tsm012** [googleforgames/agones#3870]
**What happened**:
Attempting to use the Lists features in Agones 1.41. I have a fleet deployed in agones and am attempting to use the:

`curl -d '{"capacity": "120", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

call as mentioned in the rest documentation. The list is declared on our "kind: Fleet" resource and declares a list players

```
lists:
  players:
    capacity: 20
    values:
    - player1
    - player2
    - player3
```

Once the fleet is deployed, I can run the command:

`curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

and will get the correct response.

`{"name":"players","capacity":"20","values":["player1","player2","player3"]}`

When I go to update that same list using the command:

`curl -d '{"capacity": "20", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

I get the response:

`{"name":"","capacity":"0","values":[]}`

I then check again to see if my list was updated:

`curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

but the reply seems to indicate nothing has changed.

`{"name":"players","capacity":"20","values":["player1","player2","player3"]}`

**What you expected to happen**:

I expected the list up update to reflect the data payload of 

`{"capacity": "20", "values": ["player3", "player4"]}`

**How to reproduce it (as minimally and precisely as possible)**:

Create a Fleet resource in agones and deploy it with a list declared as:

```
lists:
  players:
    capacity: 20
    values:
    - player1
    - player2
    - player3
```

shell into a game server in the fleet just deployed and verify that your initial values are in the list

```
curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players

{"name":"players","capacity":"20","values":["player1","player2","player3"]}
```

Attempt to update the list with new values

`curl -d '{"capacity": "20", "values": ["player3", "player4"]}' -H "Content-Type: application/json" -X PATCH http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players`

after running the update list call, confirm that the list has not changed

```
curl -H "Content-Type: application/json" -X GET http://localhost:${AGONES_SDK_HTTP_PORT}/v1beta1/lists/players

{"name":"players","capacity":"20","values":["player1","player2","player3"]}
```

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.41
- Kubernetes version (use `kubectl version`): 1.29 
- Cloud provider or hardware configuration: AWS EKS
- Install method (yaml/helm): Helm
- Troubleshooting guide log(s): 
- Others:

**Comment by markmandel** [comment]
Can you share the logs from the sdk-server sidecar?

If you have a gameserver or fleet.yaml you could share with a setup that easy to replicate this, would also be handy.

**Comment by markmandel** [comment]
FYI: @igooch just to make sure you see this.

**Comment by Tsm012** [comment]
Here is a simplified version of a fleet resource that you can deploy. This is happening in both AWS EKS and locally in minikube

```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-game-server-fleet
spec:
  replicas: 1
  template:
    spec:
      sdkServer:
        logLevel: Debug
      lists:
        players:
          capacity: 3
          values:
          - player1
          - player2
          - player3
      container: simple-game-server
      template:
        spec:
          containers:
            - name: simple-game-server
              image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.31
            - name: alpine   
              image: alpine/curl 
              command: ["sleep"]         # Override the container entrypoint with a simple sleep command
              args: ["1000000"]  
```


here is the tail from the agones sidecar, setting the log info to debug doesn't seem to add any additional info even though doing a describe on the pod seems to say the LOG_LEVEL environment variable is set to Debug
```
{"error":"not a valid logrus Level: \"\"","message":"Invalid LOG_LEVEL value. Defaulting to 'info'.","severity":"warning","time":"2024-06-13T23:37:24.349150707Z"}

{"ctlConf":{"GameServerName":"simple-game-server-fleet-kb5lx-lwd84","PodNamespace":"default","Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","KubeConfig":"","GracefulTermination":true,"GRPCPort":9357,"HTTPPort":9358,"LogLevel":""},"featureGates":"AutopilotPassthroughPort=false\u0026CountsAndLists=true\u0026DisableResyncOnSDKServer=true\u0026Example=false\u0026GKEAutopilotExtendedDurationPods=false\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026PortPolicyNone=false\u0026PortRanges=false\u0026RollingUpdateFix=false","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2024-06-13T23:37:24.349276227Z","version":"1.41.0"}

{"gsKey":"default/simple-game-server-fleet-kb5lx-lwd84","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2024-06-13T23:37:24.350165213Z"}

{"gsKey":"default/simple-game-server-fleet-kb5lx-lwd84","message":"Connection to Kubernetes service established","severity":"info","source":"*sdkserver.SDKServer","time":"2024-06-13T23:37:24.359130873Z","try":0}             

{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2024-06-13T23:37:24.359724909Z"}

{"gsKey":"default/simple-game-server-fleet-kb5lx-lwd84","message":"Starting workers...","queue":"agones.dev.default.simple-game-server-fleet-kb5lx-lwd84","severity":"info","source":"*sdkserver.SDKServer","time":"2024-06-13T23:37:24.460172777Z","workers":1}

{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2024-06-13T23:37:25.361356656Z"}
```
