### ISSUE TITLE
Gameserver mounts var/run/secrets/kubernetes.io/serviceaccount from empty instead of kube-api-access-xxxxx

### ISSUE THREAD

**Issue by julian-siebert** [googleforgames/agones#4060]
**What happened**:

I created a GameServer that uses an image which requires the kubernetes in-cluster-config to be available.
After doing some troubleshooting I found out that agones seems to mount the ` /var/run/secrets/kubernetes.io/serviceaccount` on the empty volume instead on the auto-created kube-api-access-xxxxx

**What you expected to happen**:

`/var/run/secrets/kubernetes.io/serviceaccount` being mounted on kube-api-access-xxxxx

**How to reproduce it (as minimally and precisely as possible)**:

Just create a GameServer. kubectl describe pod xxx should print out something like this:

```
Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from empty (ro)
```

```
Volumes:
  empty:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-jbp8v:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true

```

**Anything else we need to know?**:

Helm values:

```yaml
agones:
      controller:
        replicas: 1
      ping:
        replicas: 1
        http:
          serviceType: NodePort
        udp:
          serviceType: NodePort
      allocator:
        replicas: 2
        service:
          serviceType: NodePort
      extensions:
        replicas: 1
```

(configured for testing servers)

**Environment**:
- Agones version: 1.45.0
- Kubernetes version (use `kubectl version`): 1.30.5
- Cloud provider or hardware configuration: Talos Linux
- Install method (yaml/helm): helm
- Troubleshooting guide log(s): -
- Others: -
