### ISSUE TITLE
Feature: Script Based Autoscaler

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#4080]
I’ve had this idea floating around in my head for a while (I think it came up in a meeting?) and should really get it out 😆 and see if people like it.

**Is your feature request related to a problem? Please describe.**  
If there is a need for any kind of custom logic with an autoscaler, a webhook autoscaler is the only solution. The friction point there is that this needs to be a http service that is also hosted somewhere. Sometimes, that’s not an option, or at the very least, it would be handy to not have to deploy a whole extra service as well as Agones itself to a cluster \- but still have the ability to implement custom autoscaling logic with relative ease.

**Describe the solution you'd like**  
Be able to configure the math for autoscaling using a script that’s embedded in the `FleetAutoscaler` configuration.

My first thought is embedding Go into the yaml, via [https://github.com/traefik/yaegi](https://github.com/traefik/yaegi) , but there are a variety of scripting languages (linked below) , so something like this is a sacrificial draft:

```yaml
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: fleet-autoscaler-counter
spec:
  fleetName: fleet-example
  policy:
    type: Script
    script: |
       func Scale(r FleetAutoscaleRequest) (FleetAutoscaleResponse, error) {
           response := FleetAutoscaleResponse{
             UID = r.UID
             Scale = true
             Replicas = r.Status.AllocatedReplicas + 1
           }
           return response, nil
       }
```

Some extra options that might be needed/wanted:

* `function` \- the name of the function to use for scaling. Could have a default value of “Scale” (or similar), could also introspect the script and if there is only one function, and therefore use that one.

I do like yaegi though, since we can reuse the Go types we use inside Agones for the scripting language without as much need for interop layers.

**Describe alternatives you've considered**

Keep only the webhook autoscaler. A webhook does allow for custom logic as needed.

The only other downside to having this, is testability could be tricky. 

In theory, people could use the script library itself to write unit tests for the script contents, likely pulled from their YAML files. A *little* tricky, but definitely not impossible. We could provide an example (and we’d probably want to have one anyway for our unit tests).

**Additional context**

* [https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/](https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/)  
* [https://agones.dev/site/docs/reference/fleetautoscaler/](https://agones.dev/site/docs/reference/fleetautoscaler/)  
* [https://github.com/avelino/awesome-go?tab=readme-ov-file\#embeddable-scripting-languages](https://github.com/avelino/awesome-go?tab=readme-ov-file#embeddable-scripting-languages)

**Comment by markmandel** [comment]
Ping to update.

**Comment by markmandel** [comment]
I still think this is a good idea 😄

**Comment by markmandel** [comment]
I'm slowly pottering on this in the background. Trying to see what is possible with yaegi.

**Comment by markmandel** [comment]
I just tried out yaegi since I thought that it would be handy to straight import Agones go types... and I think it's a no-go. Only works with older Go versions, and importing the agones types is proving to be nigh impossible (a common problem with yaegi).

I looked at tengo as well, but the interop there is not as seamless as I would like. There doesn't seem to be a good pure-go Lua option with decent interop either that is actively maintained.

I was poking at other options that have good Go interop (haven't found anything that great yet), but the more I dig into this, I'm actually wondering if passing JSON in and out of a wasm module is actually the easiest (?) and most flexible way to go?

**Comment by markmandel** [comment]
https://github.com/tetratelabs/wazero looks particularly good at this.

**Comment by markmandel** [comment]
OMG, wasm is paaaaiiiinful. 😬 

Doing some more scripting language exploration - trying to find something that has really good Go interop.

* https://github.com/risor-io/risor/blob/main/examples/go/struct/main.go actually looks really promising.
* https://pkg.go.dev/github.com/dop251/goja#Runtime.ToValue might be possible -- but it looks like that may have some potential wonkiness to it. Worth trying though.

**Comment by markmandel** [comment]
Interesting conversation on Slack re: yaegi https://agones.slack.com/archives/C9DGM5DS8/p1748284398595809

**Comment by markmandel** [comment]
So chatting in Slack (see above) - we got it working! which is awesome.

A few concerns I still have with Yaegi:
1. Maintenance. Is it maintained? I'm not entirely sure. Hasn't been a release in a year.
2. https://github.com/traefik/yaegi/issues/1678 - this means you need to re-eval the script on each invocation. Not the end of the world though (since we'd probably recreate things on each invocation anyway regardless).

**Comment by markmandel** [comment]
> https://github.com/traefik/yaegi/issues/1678 - this means you need to re-eval the script on each invocation. Not the end of the world though (since we'd probably recreate things on each invocation anyway regardless).

We could also keep a cache of a compiled Program for each CRD:
https://pkg.go.dev/github.com/traefik/yaegi@v0.16.1/interp#Interpreter.Execute

**Comment by markmandel** [comment]
I made a small test bed with Riser:

```go
func TestRiserIntegration(t *testing.T) {
	_, f := defaultFixtures()
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	code := `
	print(review.Request.Name)
	review.Response.UID = review.Request.UID
`

	review := autoscalingv1.FleetAutoscaleReview{
		Request: &autoscalingv1.FleetAutoscaleRequest{
			UID:       uuid.NewUUID(),
			Name:      f.Name,
			Namespace: f.Namespace,
			Status:    f.Status,
		},
		Response: &autoscalingv1.FleetAutoscaleResponse{},
	}

	_, err := risor.Eval(ctx, code, risor.WithGlobal("review", review))
	require.NoError(t, err)
	require.Equal(t, review.Request.UID, review.Response.UID)
}
```

But it can't handle the UID type, which I think is a deal breaker 🙍🏻 

```
=== RUN   TestRiserIntegration
fleet-1
    fleetautoscalers_test.go:2748: 
        	Error Trace:	/home/mark/workspace/agones/pkg/fleetautoscalers/fleetautoscalers_test.go:2748
        	Error:      	Received unexpected error:
        	            	panic: interface conversion: interface {} is types.UID, not string
        	Test:       	TestRiserIntegration
--- FAIL: TestRiserIntegration (0.00s)
```

We did get Yaegi working (thanks @swermin and @nrwiersma), but have many of the same concerns that it looks like Traefik did:
https://traefik.io/blog/announcing-traefik-proxy-v3-rc/#:~:text=top%2Dnotch%20performance.-,Augmented%20Traefik,-Back%20in%202019

it's looking more and more like wasm is the answer.

We could support multiple scripting languages, but I don't want to add to our maintenance burder, especially as I'm not sure how maintained Yaegi actually is.

**Comment by markmandel** [comment]
Yeah. extism is definitely the way to go. It's super nice.

Here's a sample autoscaler I'm playing with to give people a taste - it's the same data in and out as the webhook autoscaler - which is nice consistency.

```go
package main

import (
	"fmt"
	"strconv"

	"github.com/extism/go-pdk"
)

const DEFAULT_BUFFER_SIZE = 5

//go:wasmexport scale
func Scale() int32 {
	var review FleetAutoscaleReview
	err := pdk.InputJSON(&review)
	if err != nil {
		pdk.SetErrorString(fmt.Sprintf("Failed to decode FleetAutoscaleReview: %v", err))
		return 1
	}

	if review.Request == nil {
		pdk.SetErrorString("FleetAutoscaleReview Request is nil")
		return 1
	}

	if review.Response == nil {
		review.Response = &FleetAutoscaleResponse{}
	}
	review.Response.UID = review.Request.UID
	review.Response.Scale = false

	// allow for an overwrite of the buffer size
	var bufferSize int32
	b, ok := pdk.GetConfig("buffer_size")
	if !ok {
		bufferSize = DEFAULT_BUFFER_SIZE
	} else {
		// convert b to an int32, and store it in bufferSize
		i, err := strconv.Atoi(b)
		if err != nil {
			pdk.SetErrorString(fmt.Sprintf("Failed to convert buffer_size to int32: %v", err))
			return 1
		}
		bufferSize = int32(i)
	}

	// Example basic logic to determine if we should scale with a simple buffer size.
	expected := bufferSize + review.Request.Status.AllocatedReplicas
	if expected != review.Request.Status.Replicas {
		review.Response.Scale = true
		review.Response.Replicas = expected
	}

	err = pdk.OutputJSON(&review)
	if err != nil {
		pdk.SetErrorString(fmt.Sprintf("Failed to encode FleetAutoscaleReview: %v", err))
		return 1
	}

	return 0
}

func main() {}
```

I'm ignoring the model `struct` values I copy pasted over and simplified, because there's no point wasm-compiling all of Agones into the binary (also, there are bits that don't compile under wasm).

This is also the yaml I'm looking at for config, what do people think?

```yaml
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: webhook-fleet-autoscaler
spec:
  fleetName: simple-game-server
  policy:
    # type of the policy - this example is Webhook
    type: Wasm
    # parameters for the wasm policy
    wasm:
      function: 'scale' # The function to call in the wasm module, defaults to 'scale'
      config: # wasm config values to pass to the wasm program on startup
        scale_buffer: 10
      valueFrom:
        configMapKeyRef:
          # The ConfigMap containing the wasm byte data
          name: autoscaler-wasm-configmap
          # Specify the key within the configMap that contains the wasm byte data
          key: data
```

* using `valueFrom` so if we want to add other ways to get at wasm data, we can (url maybe?)
* I did config variables, but not input values. Could definitely do input variables down the line, but figured one problem at a time.\
* We could also add more host functions over time as needed or wanted.

Feedback definitely appreciated.

**Comment by markmandel** [comment]
Ahaha I just ran into a snag with the above setup. ConfigMap can only hold a file 1MB in size. My basic extism example - 3MB in size.

Is a PVC really the answer 😬 ? Or just URL? It might have to be URL.

**Comment by markmandel** [comment]
Looks like URL is the way to go. Exiterm does have URL loading, but doesn't support custom ca certs like we do with the fleet autoscaler - so I'm actually thinking we lift that code from webhook autoscaler, and download the binary ourselves.

https://min.io/docs/minio/kubernetes/upstream/index.html - for testing this could definitely work. In prod, I assume most people would use S3 or a Cloud Bucket.

This would then look like:

```yaml
apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: webhook-fleet-autoscaler
spec:
  fleetName: simple-game-server
  policy:
    # type of the policy - this example is Webhook
    type: Wasm
    # parameters for the wasm policy
    wasm:
      function: 'scale' # The function to call in the wasm module, defaults to 'scale'
      config: # wasm config values to pass to the wasm program on startup
        scale_buffer: 10
      from:
        url:
          # use a service, or direct URL
          service:
            name: fileserver
            namespace: default
            path: /wasm/plugin.wasm
            # optionally can define a full URL if not hosted on cluster (or you just want to).
            # url: "https://my-bucket-storage.cloud/wasm/plugin.wasm"
            # caBundle:  optional, used for HTTPS paths with custom certs
```

I also just tweaked `valueFrom` to `from`, since `valueFrom` felt redundant` WDYT?

I do want to leave in the parent `from` element, so that if we want to add more ways to load wasm down the road we can.
