### ISSUE TITLE
Helm Schema Validation for customCertSecretPath

### ISSUE THREAD

**Issue by Joseph-Irving** [googleforgames/agones#4111]
**What happened**:
Starting from the 1.47.0 Helm chart an error occurs when trying to set `customCertSecretPath`
```
Error: values don\'t meet the specifications of the schema(s) in the following chart(s):\u000Aagones:\u000A- agones.extensions.customCertSecretPath: Invalid type. Expected: object, given: array
```
This is preventing us from using the update helm chart as we rely on custom certs.

**What you expected to happen**:
I expected the values to be applied as they did prior to this version.
I see in the schema https://github.com/googleforgames/agones/blob/v1.47.0/install/helm/agones/values.schema.json#L437
```json
            "customCertSecretPath": {
              "type": "object"
            },
```
`customCertSecretPath` has been set to type object, however I believe this should be an array as per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.30/#secretvolumesource-v1-core
`items` is an array of objects not a single object.
**How to reproduce it (as minimally and precisely as possible)**:
Try setting the customCertSecretPath value e.g
```yaml
 controller:
      customCertSecretPath:
      - key: ca.crt
        path: ca.crt
      - key: tls.crt
        path: server.crt
      - key: tls.key
        path: server.key
```

**Anything else we need to know?**:

**Environment**:
- Agones version: 1.47.0
- Kubernetes version (use `kubectl version`): v1.30.9
- Cloud provider or hardware configuration: EKS
- Install method (yaml/helm): helm
- Troubleshooting guide log(s):
- Others:
