### ISSUE TITLE
[Feature Proposal] - Allocation List Action: Pop

### ISSUE THREAD

**Issue by markmandel** [googleforgames/agones#4151]
**Is your feature request related to a problem? Please describe.**

Slack thread: https://agones.slack.com/archives/C9DGM5DS8/p1744409139256489

But TL;DR - if you have multi-tenancy game servers, and each has a different port, with existing session counters or lists, you don't know which session has which port -- especially since sessions will end in an un-ordered way.

**Describe the solution you'd like**

Let's say you have a GameServer with list of `freeSessions`, with values `session-1, session-2, session-3`, and a `capacity` of 3 (so only 3 sessions per `GameServer`), you could do something like:

```yaml
apiVersion: allocation.agones.dev/v1
kind: GameServerAllocation
spec:
  scheduling: Packed
  priorities:
    - type: List
      key: session
      order: Descending # Ensures the "freeRooms" with the most available capacity (most used) get prioritised.
  selectors:
    # Check if there is an already Allocated GameServer with room for at least one more session.
    - gameServerState: Allocated
      matchLabels:
        agones.dev/fleet: simple-game-server
      lists:
        freeSessions:
          rooms:
            minAvailable: 0
            maxAvailable: 2 # so always has to be one on the list.
   # If we can't find an Allocated GameServer, then go get a `Ready` `GameServer`.
    - gameServerState: Ready
      matchLabels:
        agones.dev/fleet: simple-game-server
      lists:
        freeSessions:
          rooms:
            minAvailable: 0
            maxAvailable: 2 # so always has to be one on the list.
  lists:
    pop:
      amount: 1 # How many to remove
      order: Front # Front is default, Back is another option. Maybe consider "random" if wanted/needed?
```

**Describe alternatives you've considered**

Leave things as they are, but it does make muilti-port multi-tenancy quite a tricky one to hand.

**Additional context**

See slack thread above.

**Link to the Agones Feature Proposal (if any)**

This is the proposal. Seems small enough to handle here.

**Discussion Link (if any)**

See above.
