### ISSUE TITLE
[Feature Proposal] - helm chart update to make the release label for the `ServiceMonitor` configurable

### ISSUE THREAD

**Issue by jessebot** [googleforgames/agones#4178]
**Is your feature request related to a problem? Please describe.**
Yes, currently Prometheus only scans for `ServiceMonitors` with the `release: kube-prometheus-stack` label, but it can't find the agones SeviceMonitors because the release label is hardcoded to the helm chart release of agones.

**Describe the solution you'd like**
I'd like to be able to configure that label and others via a parameter called `agones.metrics.serviceMonitor.labels` that accepts a map.

**Describe alternatives you've considered**
If the label isn't provided, we could also just default back to the agones helm chart release

**Additional context**
I can get this done if you'd like.

Here's some context:
https://github.com/prometheus-operator/kube-prometheus/issues/1392#issuecomment-1411719953

**Link to the Agones Feature Proposal (if any)**
The link to the AFP PR.

**Discussion Link (if any)**

**Comment by jessebot** [comment]
This would still be nice, and we could also add `agones.metrics.serviceMonitor.additonalLabels` which is something that's done in say the [external-secrets-operator helm chart](https://github.com/external-secrets/external-secrets/blob/c2bf0c0970954e4790eb03fecdc7da6f557c80a2/deploy/charts/external-secrets/values.yaml#L194), but I did find a workaround for now! In the kube-prometheus-stack helm chart you can do the following in your `values.yaml`:

```yaml
prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```
