### ISSUE TITLE
Use of HorizontalPodAutoscaler and PodDisruptionBudget for a Fleet

### ISSUE THREAD

**Issue by aLekSer** [googleforgames/agones#553]
Scale subresource was enabled in Kubernetes 1.11 as default in GKE.

Scale subresource also makes HPA and PDB available for a Fleet:
```
Scale subresource allows systems like HorizontalPodAutoscaler and PodDisruptionBudget 
interact with your new resource.
```

Also Custom metrics could be used for HPA:
 https://cloud.google.com/blog/products/gcp/beyond-cpu-horizontal-pod-autoscaling-comes-to-google-kubernetes-engine

We need to investigate how we can create HorizontalPodAutoscaler and use Agones Stackdriver metrics in order to scale a fleet. For instance, based on a percentage of the Ready Gameservers in a fleet.

Docs: https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/

The code which adds this feature for Fleet CRD could be found here: https://github.com/GoogleCloudPlatform/agones/pull/539 .

Example yaml file which creates HPA for a Fleet:
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fleet-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: "stable.agones.dev/v1alpha1"
    kind: Fleet
    name: simple-udp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
```

You can list your HPA in a usual way:
```
$ kubectl get hpa
NAME                 REFERENCE                       TARGETS         MINPODS   MAXPODS   REPLICAS   AGE 
autoscaler-webhook   Deployment/autoscaler-webhook   0%/50%          1         10        1          3d
fleet-hpa            Fleet/simple-udp                <unknown>/50%   1         10        2          34s
```
