### ISSUE TITLE
Proposal: Multi-Cluster Allocation Policies

### ISSUE THREAD

**Issue by jkowalski** [googleforgames/agones#597]
Background
----

When operating multiple Agones clusters to support world-wide game launch it is often necessary to perform multi-cluster allocations (allocations from a set of clusters instead of just one) based on defined policies.

Examples of common policies include:

* **burst to cloud** - first allocate from a fleet in a cluster located on premises but when it's out of capacity, start allocating from a fleet hosted in the cloud.
* **provider preference** - prefer certain cloud providers over others based on factors such as cost or quality of service, with the ability to fall back to others when capacity is not available
* **load spreading** - distribute allocations across clusters from different providers to limit the blast radius of an outage of a single cluster (e.g. network fiber cut)

Proposal
----

This document proposes changing how `GameServerAllocation` API works by adding support for forwarding allocation requests to other clusters based on policies that can be applied on a per-request basis.

We will add a new CRD called `GameServerAllocationPolicy` that controls how multi-cluster allocations will be performed. The policy will contain a list of clusters to allocate from with corresponding priorities and weights. The credentials for accessing those clusters will be stored in secrets.

```yaml
apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServerAllocationPolicy
metadata:
  name: my-policy
  namespace: default
spec:
  clusters:
  - name: on-prem
    priority: 1
    server: "https://some-endpoint"
    credentials: "some-secret-name"
  - name: another-cloud
    priority: 2
    weight: 100
    server: "https://some-other-endpoint"
    credentials: "some-other-secret-name"
  - name: this-cluster
    priority: 2
    weight: 300
    server: "local"
```

The name of the policy can be specified when creating `GameServerAllocation`.

```yaml
apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServerAllocation
metadata:
  generateName: my-allocation-
spec:
  policy: my-policy
  required:
    matchLabels:
      game: my-game
  preferred:
    - matchLabels:
        stable.agones.dev/fleet: green-fleet
  scheduling: Packed
  metadata:
    ...
```

If `policy` is not specified, the allocation will be attempted from the local cluster as it is done today.
 
When `policy` is present on a the `GameServerAllocation` request, the API handler would become a router that calls the specified clusters in their priority order, and for clusters with equal priority it would randomly pick a clusters, with probability of choosing a cluster proportional to its weight. If a cluster is out of capacity, the handler would try other clusters until the allocation succeeds or the list of clusters to try is exhausted.

In the example above, when the allocation request comes in, we would always try allocating from `on-prem` cluster first, because it's a cluster with highest priority.

If allocation from `on-prem` fails, we proceed to next highest priority which includes two possible clusters: `this-cluster` (with 75% probability) or `other-cloud` (with 25% probability).

Deployment Topologies
---

In a multi-cluster scenario, several allocation topologies are possible, based on a decision where to put the `GameServerAllocationPolicy` objects:

**Single Cluster Responsible For Routing**

In this mode, a single cluster is selected to server multi-cluster allocation APIs and Match Maker is pointed at its allocation endpoint. The cluster has `GameServerAllocationPolicy` that points at all other clusters. This has the benefit of simplicity, but has a single point of failure, which is the chosen cluster.

Pros:
- simple configuration of policies (one place)
- simple configuration of secrets (one place)

Cons:
- single point of failure
- secrets hosted in the cluster that's running game servers

![single routing cluster](https://user-images.githubusercontent.com/249880/52869596-dd0bb500-30fa-11e9-8951-3578258cd9e8.png)

**Dedicated Cluster Responsible For Routing**

Another option, similar to the single cluster is to create a dedicated cluster that's only responsible for allocations, but does not host game servers or fleets. This cluster will have only routing policies and secrets to talk to other clusters.

Pros:
- simplified management of policies (one cluster only)
- simplified management of secrets (one cluster only)
- no secrets are stored in clusters where game servers run

Cons:
- still single point of failure
- additional Agones cluster to manage

![dedicated routing cluster](https://user-images.githubusercontent.com/249880/52869595-dd0bb500-30fa-11e9-91e9-b70f619ed4f5.png)

**All Clusters Responsible For Routing**

In this mode, all clusters will have policies and secrets that allow them to route allocation requests to all other clusters when necessary. A global load balancer (could be a VIP or DNS-based) will randomly pick a cluster to allocate from, which will perform an extra "hop" to the cluster based on policy.

![all routing clusters](https://user-images.githubusercontent.com/249880/52869594-dd0bb500-30fa-11e9-9fee-18b3f83928ea.png)

Pros:
- resilient to cluster outages
- no additional clusters to manage

Cons:
- complex configuration of policies
- complex configuration of secrets

**Other Topologies**

Other, more complex topologies are possible, including hierarchical ones where routing-only clusters form a hierarchy, routing-only-clusters behind load-balancers, etc.
