### ISSUE TITLE
Make all yaml files in the examples directory use working configurations / images

### ISSUE THREAD

**Issue by roberthbailey** [googleforgames/agones#969]
Files to verify / update:
- [x] fleet.yaml
- [x] fleetautoscaler.yaml
- [x] gameserver.yaml
- [x] gameserverallocation.yaml
- [x] webhookfleetautoscaler.yaml
- [x] webhookfleetautoscalertls.yaml

We also need to update https://agones.dev/site/docs/examples/ for the 0.12 release to remove the working about the examples not being functional.

**Comment by roberthbailey** [comment]
webhookfleetautoscaler.yaml and webhookfleetautoscalertls.yaml are used in https://agones.dev/site/docs/getting-started/create-webhook-fleetautoscaler/ which I've gone through recently so those ones should be fine.

**Comment by roberthbailey** [comment]
The fleet.yaml file appears to be ok already:

```bash
$ kubectl apply -f https://raw.githubusercontent.com/googleforgames/agones/master/examples/fleet.yaml
fleet.agones.dev/fleet-example created
$ kubectl get gs
NAME                        STATE   ADDRESS          PORT   NODE                                     AGE
fleet-example-shz66-bmqx5   Ready   104.196.251.83   7427   gke-test-cluster-default-07171326-f5n8   8s
fleet-example-shz66-lpcdw   Ready   104.196.251.83   7087   gke-test-cluster-default-07171326-f5n8   8s
```

**Comment by roberthbailey** [comment]
Likewise, fleetautoscaler.yaml appears fine too.

**Comment by roberthbailey** [comment]
@aLekSer has a PR to fix gameserver.yaml, which just leaves gameserverallocation.yaml and the website update.

**Comment by roberthbailey** [comment]
We may also want to update the website's pages under Reference to include any updates to the files. Right now most of them inline a yaml and link to the examples folder, but it would be nice if the inlined yaml matched what was in the examples folder.

**Comment by aLekSer** [comment]
`gameserverallocation.yaml` is fine.
In order to use it we need next `fleet.yaml` configuration:
```
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: green-fleet
spec:
  replicas: 2
  template:
    metadata:
      labels:
        game: my-game
        tier: cache
    spec:
      ports:
      - name: default
        containerPort: 7654
      template:
        spec:
          containers:
          - name: simple-udp
            image: gcr.io/agones-images/udp-server:0.14
```
