### ISSUE TITLE
Fleet Image Edit causes an infinite create/destroy loop

### ISSUE THREAD

**Issue by TimoSchmechel** [googleforgames/agones#975]
**What happened**:
I created a fleet using `kubectl apply -f fleet.yaml` then edited the file to change the container image being used, afterwards it got stuck in a loop of continuously creating the new gameservers and then destroying them again. 

NOTE: This doesnt seem to happen when using `kubectl edit fleet test-fleet`

**What you expected to happen**:
I was trying to update the image used by the fleet to update the running game servers to a new build. 

**How to reproduce it (as minimally and precisely as possible)**:
Use the yaml file below and run `kubectl apply -f fleet.yaml` then wait till the server is ready, now edit the file to change the image version from 11 to 10 (or any other valid version). Run `kubectl apply -f fleet.yaml` again. Use `kubectl get gs` to watch the pods get created/destroyed forever

```
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
  name: test-fleet
spec:
  replicas: 1
  template:
    spec:
      ports:
      - name: default
        containerPort: 1234
        protocol: UDP
      template:
        spec:
          containers:
          - name: test
            image: gcr.io/agones-images/udp-server:0.11
            resources:
              limits:
                memory: "50Mi"
                cpu: "0.2"
```

**Environment**:
- Agones version: 
agones-0.11.0
- Kubernetes version (use `kubectl version`):
Client Version: v1.14.3
Server Version: v1.11.10-gke.5
- Cloud provider or hardware configuration:
GKE
- Install method (yaml/helm):
yaml
- Troubleshooting guide log(s):
- Others:
